import React from 'react'
import { Text } from "react-native"

// Total data
export const nhathuochamy = [
    { name: "Dung dịch sát khuẩn Cồn 70 độ Dr.Line (có vòi xịt)", image: "https://cdn.medigoapp.com/product/64e4f40b031749d3bc910811f152c03a./file/e9f872c1f2bc57271badc848a1c703ec", id: "0", gia: "48.000 đ/chai", nhathuoc: "Nhà thuốc Hà My", SL: 1, mota: "1. Công dụng/Chỉ định:\n- Xịt rửa tay sát khuẩn - Cồn y tế\n- Cồn sát khuẩn, làm sạch. Để khô tự nhiên\n2. Đối tượng sử dụng:\nNgười lớn và trẻ em.\n3. Liều lượng và cách dùng:\n- Cồn 70 độ rửa tay kháng khuẩn.\n4. Lưu ý khi sử dụng:\nSau khi sử dụng nhớ đậy nắp, tránh bay hơi cồn.\n5. Thành phần:\n90% v/v Ethanol.\n6. Bảo quản:\nNơi khô mát, tránh ánh sáng\n7. Hạn dùng:\nXem trên bao bì sản phẩm\n8. Phân loại sản phẩm:\nDung dịch sát khuẩn, khử khuẩn " },
    { name: "Bộ test nhanh STANDARD Q COVID-19", image: "https://cdn.didongviet.vn/pub/media/catalog/product//c/o/combo-3-dung-cu-test-nhanh-covid-19-standard-q.jpg", id: "3", gia: "200.000 đ/hộp", nhathuoc: "Nhà thuốc Hà My", SL: 1, mota: "1. Mô tả Standard Q COVID-19 Ag\nStandard Q COVID-19 Ag là xét nghiệm miễn dịch sắc ký nhanh để phát hiện định tính các kháng nguyên đặc hiệu đối với SARS-CoV-2 hiện diện trong mẫu tỵ hầu của người.\nĐây cũng là một trong những sản phẩm bộ kit test nhanh được nhiều đơn vị và cá nhân tin dùng bởi các ưu điểm:\nThời gian kiểm tra: Trong 15 ~ 30 phút\nĐộ nhạy: 84.97%\nĐộ đặc hiệu: 98.94%\nHạn sử dụng: 24 tháng\n2. Hướng dẫn sử dụng Standard Q COVID-19 Ag\nThu thập mẫu\nBước 1: Mở túi bên trong có ống nghiệm đựng dung dịch tách chiết sau đó mở nắp ống\nBước 2: Cắm ống nghiệm có chứa dung dịch vào hộp giấy dùng để đựng bộ kit\nBước 3: Lấy que tăm bông đã diệt khuẩn ra và đưa lần lượt phần đầu bông vào từng bên lỗ mũi, mỗi bên đưa sâu vào khoảng 1.5cm và xoay nhẹ khoảng 10 lần để đầu bông thấm mẫu dịch tỵ hầu\nTiến hành xét nghiệm\nBước 1: Sau khi đã lấy mẫu xong, từ từ rút tăm bông ra khỏi mũi và cắm vào ống đựng dung dịch tách chiết, ngoáy khoảng 10 lần để tách chiết mẫu dung dịch xét nghiệm\nBước 2: Dùng nắp vòi đậy chặt ống đựng dung dịch, sau đó nhỏ 3 – 4 giọt dung dịch đã chiết được lên que xét nghiệm (phần có lỗ tròn)\nBước 3: Chờ sau khoảng 15 phút kết quả sẽ được hiển thị trên que xét nghiệm\nĐọc kết quả\nKết quả của bộ kit test nhanh Standard Q COVID-19 Ag Test có thể được hiểu như sau:\nMột vạch xuất hiện tại vị trí C: Kết quả âm tính, tuy nhiên nếu đã từng tiếp xúc trực tiếp với người nhiễm Covid 19 hoặc có triệu chứng giống với Covid cần làm thêm xét nghiệm RT-PCR.\nHai vạch xuất hiện đồng thời ở cả vị trí C và T: Kết quả dương tính, cần tới bệnh viện xét nghiệm RT-PCR\nKhông có vạch nào xuất hiện ở cả 2 vị trí C và T hoặc chỉ có một vạch xuất hiện ở T: Kết quả không hợp lệ hoặc bộ kit bị lỗi\n3. Lưu ý khi sử dụng\nTất cả các dụng cụ sử dụng để xét nghiệm xong cần bỏ vào túi nilon dán chặt và xử lý như rác thải thông thường nếu kết quả âm tính.\nTrường hợp dương tính thì phải mang tới bệnh viện để được xử lý như rác thải y tế.\n4. Thành phần\nMột bộ kit test Standard Q bao gồm:\nQue tăm bông lấy mẫu đã khử trùng\nỐng nghiệm đựng dung dịch tách chiết và nắp vòi\nQue xét nghiệm (cấu tạo 2 phần: phần dùng để nhỏ dung dịch xét nghiệm và phần hiển thị kết quả)\nGiấy hướng dẫn sử dụng của nhà sản xuất" },
    { name: "Dung dịch xịt mũi Nano Salt Overate", image: "https://cdn.muabannhanh.com/asset/frontend/img/gallery/2021/06/16/60c976e051219_1623815904.jpg", id: "9", gia: "40.000 đ/hộp", nhathuoc: "Nhà thuốc Hà My", SL: 1, mota: "1. Công dụng/Chỉ định:\n- Xịt rửa, vệ sinh khoang mũi, loại bỏ gỉ mũi, chất nhầy, giúp thông thoáng, dễ thở và tạo cảm giác mát dịu.\n- Hỗ trợ ngừa khuẩn, kháng viêm, phòng ngừa sổ mũi, ngạt mũi và viêm xoang.\n2. Liều lượng và cách dùng:\n- Lắc nhẹ bình xịt, nhấn nút xịt, thiết bị xịt sẽ phun dung dịch vệ sinh mũi dưới dạng phun sương mù vào sâu bên trong khoang mũi.\n- Xịt 3-5 lần mỗi bên mũi, 3-6 lần/ngày, hoặc sử dụng nhiều hơn khi cần thiết.\n3. Lưu ý khi sử dụng:\nKhông sử dụng trong các trường hợp sau:\n- Viêm tai hoặc vừa phẫu thuật tai.\n- Rối loạn nuốt hoặc tắc nghẽn tai.\nCảnh báo và thận trọng\n- Trẻ em sử dụng phải có sự hướng dẫn của người lớn và theo sự chỉ định của bác sỹ.\n4. Thành phần:\nNước, Glycerin, Benzalkonium clorid, Sodium Chloride, Sodium benzoat, acid citric, propylene glycol, Tinh dầu bạc hà, Tween 20, nano silver và khuynh diệp, cúc tím, Hương\n5. Bảo quản:\nNơi khô ráo, thoáng mát, tránh ánh nắng trực tiếp.\n6. Hạn dùng:\n36 tháng kể từ ngày sản xuất.\n7. Phân loại sản phẩm:\nDung dịch vệ sinh tai, mũi, họng, vết loét" },
    { name: "Dụng cụ rửa mũi Natip hộp 1 cái", image: "https://cdn.medigoapp.com/product/9afa68871eb149d6a4dbc06b2fd7587b.jpg", id: "15", gia: "23.000 đ/hộp", nhathuoc: "Nhà thuốc Hà My", SL: 1 },
    { name: "Dung dịch nước muối biển Coolbi hộp 1 chai", image: "https://thuocthat.com/wp-content/uploads/2021/01/Dung-Dich-Nuoc-Muoi-Bien-Coolbi-Chai-70ml.jpg", id: "16", gia: "35.000 đ/hộp", nhathuoc: "Nhà thuốc Hà My", SL: 1 },
    { name: "Dung dịch xịt mũi NINOSAT hộp 1 chai 50", image: 'https://cf.shopee.vn/file/d3261f73bad1b215933e160ac841e5e7', id: "21", gia: "35.000 đ/hộp", nhathuoc: "Nhà thuốc Hà My", SL: 1 },
    { name: "Dung dịch sát khuẩn, khử khuẩn Providon lod", image: "https://cdn.medigoapp.com/product/05a5503fe48b4f06a3736a282ae2fceb.jpg", id: "25", gia: "7.000 đ/hộp", nhathuoc: "Nhà thuốc Hà My", SL: 1 },
    { name: "Viên sủi bổ sung vitamin C, kẽm Redoxon Double", image: "https://cdn.medigoapp.com/product/f009c5bedac14fd0bcbd55de2b3c576d.jpg", id: "28", gia: "67.000 đ/hộp", nhathuoc: "Nhà thuốc Hà My", SL: 1 },
]
export const nhathuoclongchau = [
    { name: "Máy đo nồng độ oxy trong máu Sp02 và nhịp tim", image: "https://cf.shopee.vn/file/e0413447c61b17b4e88dda0b0c18aa58", id: "1", gia: "100.000 đ/hộp", nhathuoc: "Nhà thuốc Long Châu", SL: 1, mota: "Đo chính xác, kích thước nhỏ gọn, vận hành dễ dàng, không gây đau khi đo.\n Máy tự động tắt sau 5 giây khi không nhận được tín hiệu nên rất tiết kiệm pin.\nMàn hình OLED cho độ tương phản cao, góc nhìn rộng và sắc nét.\nCông dụng\nĐo nhịp tim và SpO2, hiển thị cả dạng sóng và đồ thị với độ chính xác cao.\nĐối tượng sử dụng\nNgười lớn và trẻ em từ 12 tuổi trở lên.\nLưu ý\n- Không sử dụng cho ngón tay có vết thương hở.\n- Đọc kỹ hướng dẫn sử dụng trước khi dùng.\nBảo quản\nĐể nơi khô ráo, thoáng mát, tránh ánh nắng mặt trời trực tiếp." },
    { name: "Bông gạc đắp vết thương Bảo Thạch gói 10 miếng", image: "https://baothach.com/wp-content/uploads/photo-gallery/imported_from_media_libray//IMG_0117.jpg", id: "4", gia: "16.000 đ.gói", nhathuoc: "Nhà thuốc Long Châu", SL: 1, mota: "THÔNG TIN SẢN PHẨM:\n- Chất liệu: 100% bông tự nhiên\n- Hãng sản xuất: Bảo Thạch\n- Xuất xứ: Việt Nam\n- Bông gạc đắp vết thương bao gồm: 1 lớp bông được bọc ngoài bởi 1 lớp gạc hoặc vải không dệt.\n- Kích thước: 8cm x 17cm\n- Hàng Việt Nam chất lượng cao; Tiêu chuẩn ISO 9001\n- Quy cách: 10 miếng/gói\n CÔNG DỤNG:\n• Bông gạc đắp vết thương được sử dụng rộng rãi tại các bệnh viện, trung tâm y tế và phòng khám.\n• Sử dụng cho nhiều loại vết thương khác nhau: trày xước, vết rách, vết bỏng, vết thương sau phẫu thuật và vết loét, v.v.\n• Được dùng để thấm máu và dịch tiết trực tiếp từ vết thương, hoặc để băng bó vết thương sau khi sát trùng.\nƯU ĐIỂM SẢN PHẨM:\n- Tiệt trùng bởi khí Ethylene Oxide.\n- Sản xuất theo tiêu chuẩn Dược Điển Việt Nam.\n- Khả năng thấm hút cao và nhanh.\n- Mịn màng, mềm mại, không gây kích ứng da.\n- Thân thiện môi trường, bông trắng và sạch.\n- Nhỏ gọn, rất thuận tiện khi sử dụng.\n- Giảm nhiễm khuẩn huyết liên quan đến tiêm truyền.\n- An toàn, tiết kiệm chi phí điều trị.\nHƯỚNG DẪN SỬ DỤNG:\n- Vệ sinh sạch sẽ vết thương bằng thuốc sát khuẩn, khử trùng\n- Xé bao bì theo đường cắt sẵn\n- Đắp gạc lên vết thương cần chăm sóc\n*Chú ý: Vết thương phải được lau rửa sạch bằng thuốc sát trùng.\nBẢO QUẢN:\n- Để sản phẩm nơi khô ráo, sạch sẽ, tránh xa tầm tay trẻ em, vệ sinh tay trước khi dùng." },
    { name: "Nhiệt kế thủy ngân Tokyo Clinical Thermometer", image: "https://vivita.vn/wp-content/uploads/2021/03/nhiet-ke-thuy-ngan-TOKYO-6-1.jpg", id: "18", gia: "35.000 đ/hộp", nhathuoc: "Nhà thuốc Long Châu", SL: 1 },
    { name: "Thuốc giảm đau, hạ sốt Phaanedol Plus", image: "https://vinmec-prod.s3.amazonaws.com/images/20220408_012920_862586_phaanedol-plus-extr.max-1800x1800.png", id: "30", gia: "15.000 đ/hộp", nhathuoc: "Nhà thuốc Long Châu", SL: 1 },
    { name: "Viên sủi bổ sung vitamin tổng hợp Plusssz Gold", image: "https://images.fpt.shop/unsafe/fit-in/600x600/filters:quality(90):fill(white)/nhathuoclongchau.com/images/product/2020/07/00006012-plusssz-max-multi-5229-5f21_large.JPG", id: "35", gia: "32.000 đ/hộp", nhathuoc: "Nhà thuốc Long Châu", SL: 1 },
    { name: "Xịt họng thảo dược trị ho, viêm họng Eugica hộp 1", image: "https://images.fpt.shop/unsafe/fit-in/600x600/filters:quality(90):fill(white)/nhathuoclongchau.com/images/product/2021/12/00020443-eugica-mouth-spay-10ml-mega-9606-61a9_large.jpg", id: "37", gia: "44.000 đ/hộp", nhathuoc: "Nhà thuốc Long Châu", SL: 1 },
]

export const nhathuocminhchau = [
    { name: "Nước muối sinh lý Nam Hà Natri Clorid 0.9% chai", image: "https://www.ytecaocap.com/uploads/Products/2653/m_2653.jpg", id: "2", gia: "12.000 đ/chai", nhathuoc: "Nhà thuốc Minh Châu", SL: 1, mota: "Thành phần:\n- Natri clorid 4.5 gr.\n- Nước tinh khiết vừa đủ 500 ml.\nCông dụng:\n- Rửa vết thương hở và kín.\n- Súc miệng để vệ sinh răng miệng, họng mỗi ngày.\nCách dùng:\n- Súc miệng: Ngậm 20 - 30 ml không pha loãng, súc kỹ trong khoảng 30 giây rồi nhổ đi, ngày 2 - 3 lần.\n- Rửa mắt, mũi, tai và các vết thương mẩn ngứa, dị ứng: Dùng bông hoặc gạc mềm sạch tẩm dung dịch rửa ngày 3 - 4 lần.\n - Rửa mặt để loại bỏ mụn trứng cá và bụi bẩn, làm sáng da. \n - Làm sáng mắt: Ngâm mặt trong chậu nước muối, mở mắt, đảo mắt lên xuống để nước muối rửa mắt. Ngày rửa một lần, liên tục trong 2 tuần\n Bảo quản: \nNơi khô mát, tránh ánh sáng, xa tầm tay trẻ em." },
    { name: "Miếng dán hạ sốt Lion Hiepita For Child hộp 8 miếng", image: "https://nhathuoclongchau.com/images/product/2019/10/00021682-mieng-dan-ha-sot-lion-hiepita-for-child-8-goi-x-2-mieng-8063-5d9e_large.JPG", id: "6", gia: "250.000 đ/hộp", nhathuoc: "Nhà thuốc Minh Châu", SL: 1, mota: "1. Mô tả:\nMiếng dán hạ sốt Lion Hiepita For Child giúp bé hạ sốt nhanh chóng. Sản phẩm có phủ lớp gel mát lạnh giúp tỏa nhiệt và làm mát đến 8 giờ đồng hồ, mang đến cho bé cảm giác dễ chịu và thoải mái tuyệt đối.\n2. Công dụng/Chỉ định:\n- Miếng dán hạ sốt Lion Hiepita For Child có công dụng giúp bé hạ sốt nhanh chóng, phòng ngừa những cơn co giật cũng như những biến chứng nguy hiểm do sốt cao gây ra.\n3. Đối tượng sử dụng:\nDùng được cho trẻ sơ sinh và trẻ nhỏ.\n4. Liều lượng và cách dùng:\n- Giữ cho vùng da khô ráo và sử dụng miếng dán ngay sau khi mở gói.\n- Gỡ bỏ miếng dán phim và dán lên vùng da cần làm mát (trán).\n- Thay miếng dán mới sau mỗi 8 giờ sử dụng.\n5. Lưu ý khi sử dụng:\n- Sử dụng theo đúng hướng dẫn.\n- Phải có người lớn giám sát khi sử dụng.\n- Chỉ sử dụng ngoài da, không sử dụng lên vết thương hở, mắt, niêm mạc... Dừng ngay nếu có triệu chứng phát ban, dị ứng.\n- Sản phẩm này không phải là thuốc. Nếu sốt kéo dài, vui lòng liên hệ ngay với bác sĩ\n6. Bảo quản:\n- Bảo quản nơi khô ráo thoáng mát, tránh tiếp xúc với không khí, tránh ánh nắng trực tiếp, nơi có nhiệt độ cao.\n7. Hạn dùng:\nXem trên bao bì.\n8. Phân loại sản phẩm:\nMiếng dán" },
    { name: "Băng keo lụa Zilgo Silk 1.25cm x 5m hộp 1 cuộn", image: "https://alphabetpharma.com.vn/image/cache/catalog/alphabet-pharma/1181-800x800.jpg", id: "7", gia: "12.000 đ/hộp", nhathuoc: "Nhà thuốc Minh Châu", SL: 1, mota: "1. Công dụng/Chỉ định:\nBăng các vết thương trong phẩu thuật, cố định kim truyền, ống thông tiểu, dụng cụ y khoa,..\n2. Liều lượng và cách dùng:\nGiữ sạch da và khô trước khi dán băng dính.\n3. Thành phần:\n- ¬Chất nền: băng vải lụa / hoặc PE (polyethylene);\n- Chất dính: là keo nóng chảy dạng hạt.\n4. Bảo quản:\nNơi thoáng mát và khô ráo.\n5. Hạn dùng:\n36 tháng kể từ ngày sản xuất.\n6. Phân loại sản phẩm:\nBông, băng, gạc" },
    { name: "Miếng dán hạ sốt NHA ĐAM hộp 3 gói x 2", image: "https://cf.shopee.vn/file/51bfc73101de3a797eb31e18b1a88969", id: "16", gia: "40.000 đ/hộp", nhathuoc: "Nhà thuốc Minh Châu", SL: 1 },
    { name: "Thuốc nhỏ mắt - nhỏ mũi Natri Clorid 0.9%", image: "https://sieuthithuocdongy.vn/upload/images/nuoc-muoi-nho-mat-natri-clorid-0-9-pharmedic-chai-10ml.jpg", id: "22", gia: "3000 đ/hộp", nhathuoc: "Nhà thuốc Minh Châu", SL: 1 },
    { name: "Cao dán giảm đau Salonpas hộp 12 miếng", image: "https://cf.shopee.vn/file/d1393b7b65ce3c8f13815e6bc0d59719", id: "24", gia: "12.000 đ/hộp", nhathuoc: "Nhà thuốc Minh Châu", SL: 1 },
    { name: "Thuốc chống dị ứng Xyzal hộp 10 viên", image: "https://vinmec-prod.s3.amazonaws.com/images/20210320_033024_552794_thuoc-Xyzal.max-1800x1800.jpg", id: "29", gia: "79.000 đ/hộp", nhathuoc: "Nhà thuốc Minh Châu", SL: 1 },
    { name: "Viên sủi Vitamed DIAMOND (hương cam)", image: "https://cdn.medigoapp.com/product/1c90b8adb5d944dbb5ea7111252ec0b0.jpeg", id: "32", gia: "75.000 đ/tuýp", nhathuoc: "Nhà thuốc Minh Châu", SL: 1 },
    { name: "Viên sủi đề kháng C Multi", image: "https://vivita.vn/wp-content/uploads/2021/08/bo-doi-vien-sui-c-xutali-va-multi-2.jpg", id: "39", gia: "62.000 đ/hộp", nhathuoc: "Nhà thuốc Minh Châu", SL: 1 },
]

export const nhathuocngoclong = [
    { name: "Nhiệt kế thủy ngân Lilika hộp 1 cái", image: "https://cf.shopee.vn/file/03bcf13d962bd2d1d8ec396758139ce2", id: "5", gia: "24.000 đ/hộp", nhathuoc: "Nhà thuốc Ngọc Long", SL: 1, mota: "1. Công dụng/Chỉ định:\nDùng đo nhiệt độ cơ thể ở miệng, nách.\n2. Liều lượng và cách dùng:\nCách sử dụng:\nCầm chắc nhiệt kế dọc theo ngón cái và ngón trỏ rồi lắc nhẹ vài lần để thủy ngân dồn hết về phía bầu inox sao cho cột thủy ngân nằm dưới vạch 35 độ C là được.\nCách đo:\n- Đo bằng đường miệng: Đặt đầu có bầu inox dưới lưỡi trong ít nhất 5 phút rồi ngậm miệng lại. Không nói hoặc cắn nhiệt kế trong khi đo. KHÔNG được dùng cách đo này cho trẻ em.\n- Đo dưới nách hoặc bẹn: Đặt đầu có bầu inox vào giữa 2 lớp da trong 5 phút. Giữ nhiệt kế nằm ổn định tại một vị trí trong suốt thời gian đo.\n3. Bảo quản:\nXem trên bao bì sản phẩm.\n4. Hạn dùng:\nXem trên bao bì sản phẩm.\n5. Phân loại sản phẩm:\nNhiệt kế" },
    { name: "Bộ test nhanh BIOHUB COVID-19 Ag Home Test", image: "https://cdn.medigoapp.com/product/biohub_2_7afb9b22b1.jpg", id: "8", gia: "85.000 đ/hộp", nhathuoc: "Nhà thuốc Ngọc Long", SL: 1, mota: "1. Công dụng/Chỉ định:\nPhát hiện kháng nguyên SARS-CoV-2 trong trong mẫu phết dịch dịch tỵ hầu của người\n2. Đối tượng sử dụng:\nDành cho mọi đối tượng\n3. Liều lượng và cách dùng:\n+ Sự hiện diện 2 vạch là vạch chứng (C) và vạch thử (T) trong cửa sổ kết quà cho biết kết quả dương tính\n+ Sự hiện diện của duy nhất vạch chứng (C) trong cửa sổ kết quả cho biết kết quả âm tính\n+ Nếu vạch (C) không hiển thị trong cửa sổ kết quả sau thực hiện xét nghiệm, kết quả được xem là không hợp lệ. Khuyến nghị để thực hiện một xét nghiệm mới.\n4. Thành phần:\nHộp 1 que test và các dụng cụ đi kèm\n5. Bảo quản:\nĐối với dung dịch đệm chạy mẫu: 2 - 3°C. Đối với que thử, thành phẩm: Bảo quản nhiệt độ phòng đảm bảo thông thoáng, tránh ánh nắng trực tiếp.\n6. Hạn dùng:\n3 năm kể từ ngày sản xuất\n7. Phân loại sản phẩm:\nBộ test nhanh" },
    { name: "Khẩu trang y tế N95 Cửu Long hộp 10 cái", image: "https://cf.shopee.vn/file/66dcd46aba6ab949fb562f27d3d0f972", id: "11", gia: "30.000 đ/hộp", nhathuoc: "Nhà thuốc Ngọc Long", SL: 1, mota: "1. Mô tả:\nKhẩu trang y tế N95 Cửu Long hộp 10 cái dày dặn, kháng khuẩn, an toàn\n2. Công dụng/Chỉ định:\n• Đeo êm hơn, dây đeo thoải mái hơn\n•Dây đeo có độ đàn hồi cao, ít tạo áp lực lên tai và mặt, tránh gây khó chịu khi sử dụng trong thời gian dài.\n•Thiết kế thông minh có nẹp mũi dạng ấn có thể giúp ôm khít sống mũi, giảm sương mù trên kính mắt.\n•Thoáng khí, thoát ẩm với lớp lọc có thể ngăn chặn tốt hơn các hạt nhỏ trong không khí và lọc nó, giảm cảm giác ẩm ướt khi đeo khẩu trang.\n 3. Đối tượng sử dụng:\nNgười lớn\n4. Liều lượng và cách dùng:\nĐể đạt u quả cao nhất trong việc lọc bụi mịn thì cách đeo khẩu trang và thiết kế của khẩu trang là rất quan trọng. Khi đeo cần để khẩu trang phủ kín hoàn toàn mũi và cằm, điều chỉnh kẹp mũi sao cho viền khẩu trang ôm khít khuôn mặt.\n5. Lưu ý khi sử dụng:\nKhuyến cáo: không nên giặt khẩu trang\n6. Thành phần:\nSử dụng công nghệ hút tĩnh điện có khả năng lọc được 95% các hạt có kích thước siêu nhỏ đến 0.3μm\n7. Bảo quản:\nNơi khô ráo thoáng mát.\n8. Hạn dùng:\n36 tháng kể từ ngày sản xuất\n9. Phân loại sản phẩm:\nKhẩu trang y tế" },
    { name: "Bộ kit test nhanh COVID-19 Labnovation", image: "https://cf.shopee.vn/file/707a58399bb8bbd0dd28092b46dbc571", id: "13", gia: "1.200.000 đ/hộp", nhathuoc: "Nhà thuốc Ngọc Long", SL: 1 },
    { name: "Kính chắn giọt bắn Boxtox hộp 1 cái", image: "https://cf.shopee.vn/file/844da3fbf18c7506dd84d08ebceb90e0", id: "20", gia: "20.000 đ/hộp", nhathuoc: "Nhà thuốc Ngọc Long", SL: 1 },
    { name: "Thuốc trị tiêu chảy, đau dạ dày tá tràng ruột", image: "https://img.thuocbietduoc.com.vn/images/drugs/2018/12/Smeclife_21-311218.jpg", id: "23", gia: "5.000 đ/hộp", nhathuoc: "Nhà thuốc Ngọc Long", SL: 1 },
    { name: "Bổ sung lợi khuẩn Enteropromina hộp 4 vỉ x 5 ống x 5ml", image: "https://thuocdantoc.vn/wp-content/uploads/2019/03/enterogermina.jpg", id: "36", gia: "5.000 đ/ống", nhathuoc: "Nhà thuốc Ngọc Long", SL: 1 },
    { name: "Cao lỏng thảo mộc Đông Trùng Bổ Phổi Greenlung", image: "https://cdn.medigoapp.com/product/dong_trung_bo_phoi_bbdb4f5bde.png", id: "38", gia: "75.000 đ/hộp", nhathuoc: "Nhà thuốc Ngọc Long", SL: 1 },
    { name: "Xịt họng Bổ Phế Nam Hà hộp 1 chai 30ml", image: "https://salt.tikicdn.com/cache/400x400/ts/product/f1/44/a1/22a088d73305b0c3c03a0396f4f04c1a.jpg", id: "40", gia: "62.000 đ/hộp", nhathuoc: "Nhà thuốc Ngọc Long", SL: 1 },


]

export const nhathuoclenguyen = [
    { name: "Khẩu trang y tế MEDIPRO màu xanh hộp 50 cái", image: "https://cdn.medigoapp.com/product/3586de85e2544271adc4a7a89e3df7cf.jpg", id: "10", gia: "50.000 đ/hộp", nhathuoc: "Nhà thuốc Lê Nguyên", SL: 1, mota: "1. Mô tả:\nKhẩu trang y tế MediPro là loại Face Mask không chỉ giúp người sử dụng chống nắng, tránh bụi bẩn mà nó còn là một trong những loại khẩu trang kháng khuẩn, không gây dị ứng và giúp cho người dùng phòng chống dịch cúm hay virus gây hại. Theo các chuyên gia thì khẩu trang Medi Pro có hiệu quả cực tốt đối với những môi trường bụi ở mức độ vừa và nhẹ giảm được 99.9% khói bụi và vi khuẩn.\n2. Công dụng/Chỉ định:\nViệc bạn sử dụng khẩu trang kháng khuẩn MediPro không chỉ giúp chống lại những cái nắng, bụi bẩn khi đi đường mà Medi Pro còn giúp cho người dùng ngăn ngừa được các bệnh thường lây qua đường hô hấp. Đây là một trong những sản phẩm sử dụng 1 lần để có thể đạt được hiệu quả tốt nhất.\nKhẩu trang kháng khuẩn MediPro này được có tác dụng cực kỳ lớn vào mùa lạnh khi mà những đợt dịch cúm hay tái phát giúp cho bảo vệ cơ thể người sử dụng tránh khỏi những nguồn bệnh hơn.\n3. Liều lượng và cách dùng:\nBước 1: Sau khi mua hộp khẩu trang y tế MediPro các bạn lấy một chiếc mà mình dùng và lấy hai tay kéo chiếc khẩu trang MediPro sang hai bên và áp sát vào mặt\nBước 2: Tiếp theo ở tay phải các bạn giữ chiếc khẩu trang MediPro còn tay trái đeo dây của sản phẩm này vào tai bên trái\nBước 3: Khi đã định hình xong các bạn kéo nhẹ cánh dưới của MediPro sao cho nó quá cằm một chút, ở gọng chì bên trên chỗ mũi bạn dùng tay bóp thanh chì này sao cho vừa khít với sống mũi\n4. Bảo quản:\nNơi khô, thoáng mát\n5. Hạn dùng:\nXem trên bao bì\n6. Phân loại sản phẩm:\nKhẩu trang y tế" },
    { name: "Khẩu trang y tế N95 GOBETA hộp 30 cái", image: "https://cdn.medigoapp.com/product/208389e3067e4fd58493175785be4181.jpg", id: "12", gia: "330.000 đ/hộp", nhathuoc: "Nhà thuốc Lê Nguyên", SL: 1, mota: "1. Mô tả:\nNgoài việc giúp che nắng, ngăn bụi, giảm được mùi khói xe, khí thải độc hại… đeo khẩu trang còn có 2 mục đích quan trọng khác là ngăn chặn mầm bệnh từ người bệnh không phát tán ra bên ngoài và nhằm bảo vệ chính bản thân người mang khẩu trang tránh phải một số bệnh truyền nhiễm qua đường hô hấp từ người khác.\n2. Công dụng/Chỉ định:\nĐây là loại khẩu trang bảo hộ tự lọc, phù hợp để lọc các hạt rất nhỏ trong không khí và ngăn ngừa các giọt bắn trong môi trường làm việc hằng ngày.\n3. Liều lượng và cách dùng:\nBước 1: Sử dụng cả hai tay, nhẹ nhàng kéo mở mặt nạ và đưa sát vào mặt.\nBước 2: Giữ mặt nạ bằng tay phải, dùng tay trái kéo dây đeo qua tai trái.\nBước 3: Nhẹ nhàng kéo cạnh dưới xuống để che cằm, sau đó dùng hai ngón tay ấn xuống nẹp mũi.\nBước 4: Điều chỉnh mặt nạ để đảm bảo phù hợp.\n4. Thành phần:\nLớp thứ 1: Vải không dệt ; Định lượng 30 g/m2 xuất xứ Việt Nam/Hàn Quốc/Thổ Nhĩ Kỳ.\nLớp thứ 2: Giấy kháng khuẩn; Định lượng 30 g/m2 xuất xứ Mỹ;\nLớp thứ 3: Bông; Định lượng 30 g/m2 xuất xứ Việt Nam\nLớp thứ 4: Giấy kháng khuẩn; Định lượng 30 g/m2 xuất xứ Mỹ;\nLớp thứ 5: Vải không dệt ; Định lượng 30 g/m2 xuất xứ Việt Nam/Hàn Quốc/Thổ Nhĩ Kỳ.\n5. Hạn dùng:\nXem trên bao bì\n6. Phân loại sản phẩm:\nKhẩu trang y tế" },
    { name: "Thuốc giảm đau, hạ sốt Tylenol 8 hour hộp 5 vỉ x10", image: "https://nhathuoclongchau.com/images/product/2018/06/00010102-tylenol-8-hour-2035-5b30_large.JPG", id: "27", gia: "150.000 đ/hộp", nhathuoc: "Nhà thuốc Lê Nguyên", SL: 1 },

]

export const nhathuocgreenpharma = [
    { name: "Dung dịch vệ sinh mũi ClariCare Daily Nasal", image: "https://cdn.medigoapp.com/product/Clari_Care_Packshot_100ml_with_can_1_0b79f14ec3.webp", id: "14", gia: "128.000 đ/hộp", nhathuoc: "Nhà thuốc Green Pharma", SL: 1 },
    { name: "Xịt họng keo ong Thái Sơn hộp 1 chai 20ml", image: "https://cf.shopee.vn/file/a4e7f8017d3d41c6e41a795c80785d15", id: "31", gia: "90.000 đ/hộp", nhathuoc: "Nhà thuốc Green Pharma", SL: 1 },
    { name: "Men vi sinh Bacibio Extra hộp 20 ống", image: "https://cdn.medigoapp.com/product/2cf2089940574f3b8cf78eaf7d3cb634.jpg", id: "33", gia: "105.000 đ/hộp", nhathuoc: "Nhà thuốc Long Châu", SL: 1 },
    { name: "Viên sủi bổ sung vitamin và kẽm Multi Green C", image: "https://cf.shopee.vn/file/635ec7caaf8e82b2b2018b1e74b9d0f2_tn", id: "34", gia: "35.000 đ/hộp", nhathuoc: "Nhà thuốc Green Pharma", SL: 1 },

]

export const nhathuocthuytrang = [
    { name: "Nhiệt kế điện tử hồng ngoại Infrared", image: "https://healthvietnam.vn/photos/177/15b66b72a9e851b608f9.jpg", id: "17", gia: "220.000 đ/hộp", nhathuoc: "Nhà thuốc Thùy Trang", SL: 1 },
    { name: "Thuốc tẩy giun Fugacar hộp 1 viên", image: "https://centralpharmacy.vn/filemanager/data-images/2020/11/04/fugacar_2.jpg", id: "26", gia: "18.000 đ/hộp", nhathuoc: "Nhà thuốc Thùy Trang", SL: 1 },
]

export const Totaldate = [
    { name: "Dung dịch sát khuẩn Cồn 70 độ Dr.Line (có vòi xịt)", image: "https://cdn.medigoapp.com/product/64e4f40b031749d3bc910811f152c03a./file/e9f872c1f2bc57271badc848a1c703ec", id: "0", gia: "48.000 đ/chai", nhathuoc: "Nhà thuốc Hà My", SL: 1, mota: "1. Công dụng/Chỉ định:\n- Xịt rửa tay sát khuẩn - Cồn y tế\n- Cồn sát khuẩn, làm sạch. Để khô tự nhiên\n2. Đối tượng sử dụng:\nNgười lớn và trẻ em.\n3. Liều lượng và cách dùng:\n- Cồn 70 độ rửa tay kháng khuẩn.\n4. Lưu ý khi sử dụng:\nSau khi sử dụng nhớ đậy nắp, tránh bay hơi cồn.\n5. Thành phần:\n90% v/v Ethanol.\n6. Bảo quản:\nNơi khô mát, tránh ánh sáng\n7. Hạn dùng:\nXem trên bao bì sản phẩm\n8. Phân loại sản phẩm:\nDung dịch sát khuẩn, khử khuẩn " },
    { name: "Máy đo nồng độ oxy trong máu Sp02 và nhịp tim", image: "https://cf.shopee.vn/file/e0413447c61b17b4e88dda0b0c18aa58", id: "1", gia: "100.000 đ/hộp", nhathuoc: "Nhà thuốc Long Châu", SL: 1, mota: "Đo chính xác, kích thước nhỏ gọn, vận hành dễ dàng, không gây đau khi đo.\n Máy tự động tắt sau 5 giây khi không nhận được tín hiệu nên rất tiết kiệm pin.\nMàn hình OLED cho độ tương phản cao, góc nhìn rộng và sắc nét.\nCông dụng\nĐo nhịp tim và SpO2, hiển thị cả dạng sóng và đồ thị với độ chính xác cao.\nĐối tượng sử dụng\nNgười lớn và trẻ em từ 12 tuổi trở lên.\nLưu ý\n- Không sử dụng cho ngón tay có vết thương hở.\n- Đọc kỹ hướng dẫn sử dụng trước khi dùng.\nBảo quản\nĐể nơi khô ráo, thoáng mát, tránh ánh nắng mặt trời trực tiếp." },
    { name: "Nước muối sinh lý Nam Hà Natri Clorid 0.9% chai", image: "https://www.ytecaocap.com/uploads/Products/2653/m_2653.jpg", id: "2", gia: "12.000 đ/chai", nhathuoc: "Nhà thuốc Minh Châu", SL: 1, mota: "Thành phần:\n- Natri clorid 4.5 gr.\n- Nước tinh khiết vừa đủ 500 ml.\nCông dụng:\n- Rửa vết thương hở và kín.\n- Súc miệng để vệ sinh răng miệng, họng mỗi ngày.\nCách dùng:\n- Súc miệng: Ngậm 20 - 30 ml không pha loãng, súc kỹ trong khoảng 30 giây rồi nhổ đi, ngày 2 - 3 lần.\n- Rửa mắt, mũi, tai và các vết thương mẩn ngứa, dị ứng: Dùng bông hoặc gạc mềm sạch tẩm dung dịch rửa ngày 3 - 4 lần.\n - Rửa mặt để loại bỏ mụn trứng cá và bụi bẩn, làm sáng da. \n - Làm sáng mắt: Ngâm mặt trong chậu nước muối, mở mắt, đảo mắt lên xuống để nước muối rửa mắt. Ngày rửa một lần, liên tục trong 2 tuần\n Bảo quản: \nNơi khô mát, tránh ánh sáng, xa tầm tay trẻ em." },
    { name: "Bộ test nhanh STANDARD Q COVID-19", image: "https://cdn.didongviet.vn/pub/media/catalog/product//c/o/combo-3-dung-cu-test-nhanh-covid-19-standard-q.jpg", id: "3", gia: "200.000 đ/hộp", nhathuoc: "Nhà thuốc Hà My", SL: 1, mota: "1. Mô tả Standard Q COVID-19 Ag\nStandard Q COVID-19 Ag là xét nghiệm miễn dịch sắc ký nhanh để phát hiện định tính các kháng nguyên đặc hiệu đối với SARS-CoV-2 hiện diện trong mẫu tỵ hầu của người.\nĐây cũng là một trong những sản phẩm bộ kit test nhanh được nhiều đơn vị và cá nhân tin dùng bởi các ưu điểm:\nThời gian kiểm tra: Trong 15 ~ 30 phút\nĐộ nhạy: 84.97%\nĐộ đặc hiệu: 98.94%\nHạn sử dụng: 24 tháng\n2. Hướng dẫn sử dụng Standard Q COVID-19 Ag\nThu thập mẫu\nBước 1: Mở túi bên trong có ống nghiệm đựng dung dịch tách chiết sau đó mở nắp ống\nBước 2: Cắm ống nghiệm có chứa dung dịch vào hộp giấy dùng để đựng bộ kit\nBước 3: Lấy que tăm bông đã diệt khuẩn ra và đưa lần lượt phần đầu bông vào từng bên lỗ mũi, mỗi bên đưa sâu vào khoảng 1.5cm và xoay nhẹ khoảng 10 lần để đầu bông thấm mẫu dịch tỵ hầu\nTiến hành xét nghiệm\nBước 1: Sau khi đã lấy mẫu xong, từ từ rút tăm bông ra khỏi mũi và cắm vào ống đựng dung dịch tách chiết, ngoáy khoảng 10 lần để tách chiết mẫu dung dịch xét nghiệm\nBước 2: Dùng nắp vòi đậy chặt ống đựng dung dịch, sau đó nhỏ 3 – 4 giọt dung dịch đã chiết được lên que xét nghiệm (phần có lỗ tròn)\nBước 3: Chờ sau khoảng 15 phút kết quả sẽ được hiển thị trên que xét nghiệm\nĐọc kết quả\nKết quả của bộ kit test nhanh Standard Q COVID-19 Ag Test có thể được hiểu như sau:\nMột vạch xuất hiện tại vị trí C: Kết quả âm tính, tuy nhiên nếu đã từng tiếp xúc trực tiếp với người nhiễm Covid 19 hoặc có triệu chứng giống với Covid cần làm thêm xét nghiệm RT-PCR.\nHai vạch xuất hiện đồng thời ở cả vị trí C và T: Kết quả dương tính, cần tới bệnh viện xét nghiệm RT-PCR\nKhông có vạch nào xuất hiện ở cả 2 vị trí C và T hoặc chỉ có một vạch xuất hiện ở T: Kết quả không hợp lệ hoặc bộ kit bị lỗi\n3. Lưu ý khi sử dụng\nTất cả các dụng cụ sử dụng để xét nghiệm xong cần bỏ vào túi nilon dán chặt và xử lý như rác thải thông thường nếu kết quả âm tính.\nTrường hợp dương tính thì phải mang tới bệnh viện để được xử lý như rác thải y tế.\n4. Thành phần\nMột bộ kit test Standard Q bao gồm:\nQue tăm bông lấy mẫu đã khử trùng\nỐng nghiệm đựng dung dịch tách chiết và nắp vòi\nQue xét nghiệm (cấu tạo 2 phần: phần dùng để nhỏ dung dịch xét nghiệm và phần hiển thị kết quả)\nGiấy hướng dẫn sử dụng của nhà sản xuất" },
    { name: "Bông gạc đắp vết thương Bảo Thạch gói 10 miếng", image: "https://baothach.com/wp-content/uploads/photo-gallery/imported_from_media_libray//IMG_0117.jpg", id: "4", gia: "16.000 đ.gói", nhathuoc: "Nhà thuốc Long Châu", SL: 1, mota: "THÔNG TIN SẢN PHẨM:\n- Chất liệu: 100% bông tự nhiên\n- Hãng sản xuất: Bảo Thạch\n- Xuất xứ: Việt Nam\n- Bông gạc đắp vết thương bao gồm: 1 lớp bông được bọc ngoài bởi 1 lớp gạc hoặc vải không dệt.\n- Kích thước: 8cm x 17cm\n- Hàng Việt Nam chất lượng cao; Tiêu chuẩn ISO 9001\n- Quy cách: 10 miếng/gói\n CÔNG DỤNG:\n• Bông gạc đắp vết thương được sử dụng rộng rãi tại các bệnh viện, trung tâm y tế và phòng khám.\n• Sử dụng cho nhiều loại vết thương khác nhau: trày xước, vết rách, vết bỏng, vết thương sau phẫu thuật và vết loét, v.v.\n• Được dùng để thấm máu và dịch tiết trực tiếp từ vết thương, hoặc để băng bó vết thương sau khi sát trùng.\nƯU ĐIỂM SẢN PHẨM:\n- Tiệt trùng bởi khí Ethylene Oxide.\n- Sản xuất theo tiêu chuẩn Dược Điển Việt Nam.\n- Khả năng thấm hút cao và nhanh.\n- Mịn màng, mềm mại, không gây kích ứng da.\n- Thân thiện môi trường, bông trắng và sạch.\n- Nhỏ gọn, rất thuận tiện khi sử dụng.\n- Giảm nhiễm khuẩn huyết liên quan đến tiêm truyền.\n- An toàn, tiết kiệm chi phí điều trị.\nHƯỚNG DẪN SỬ DỤNG:\n- Vệ sinh sạch sẽ vết thương bằng thuốc sát khuẩn, khử trùng\n- Xé bao bì theo đường cắt sẵn\n- Đắp gạc lên vết thương cần chăm sóc\n*Chú ý: Vết thương phải được lau rửa sạch bằng thuốc sát trùng.\nBẢO QUẢN:\n- Để sản phẩm nơi khô ráo, sạch sẽ, tránh xa tầm tay trẻ em, vệ sinh tay trước khi dùng." },
    { name: "Nhiệt kế thủy ngân Lilika hộp 1 cái", image: "https://cf.shopee.vn/file/03bcf13d962bd2d1d8ec396758139ce2", id: "5", gia: "24.000 đ/hộp", nhathuoc: "Nhà thuốc Ngọc Long", SL: 1, mota: "1. Công dụng/Chỉ định:\nDùng đo nhiệt độ cơ thể ở miệng, nách.\n2. Liều lượng và cách dùng:\nCách sử dụng:\nCầm chắc nhiệt kế dọc theo ngón cái và ngón trỏ rồi lắc nhẹ vài lần để thủy ngân dồn hết về phía bầu inox sao cho cột thủy ngân nằm dưới vạch 35 độ C là được.\nCách đo:\n- Đo bằng đường miệng: Đặt đầu có bầu inox dưới lưỡi trong ít nhất 5 phút rồi ngậm miệng lại. Không nói hoặc cắn nhiệt kế trong khi đo. KHÔNG được dùng cách đo này cho trẻ em.\n- Đo dưới nách hoặc bẹn: Đặt đầu có bầu inox vào giữa 2 lớp da trong 5 phút. Giữ nhiệt kế nằm ổn định tại một vị trí trong suốt thời gian đo.\n3. Bảo quản:\nXem trên bao bì sản phẩm.\n4. Hạn dùng:\nXem trên bao bì sản phẩm.\n5. Phân loại sản phẩm:\nNhiệt kế" },
    { name: "Miếng dán hạ sốt Lion Hiepita For Child hộp 8 miếng", image: "https://nhathuoclongchau.com/images/product/2019/10/00021682-mieng-dan-ha-sot-lion-hiepita-for-child-8-goi-x-2-mieng-8063-5d9e_large.JPG", id: "6", gia: "250.000 đ/hộp", nhathuoc: "Nhà thuốc Minh Châu", SL: 1, mota: "1. Mô tả:\nMiếng dán hạ sốt Lion Hiepita For Child giúp bé hạ sốt nhanh chóng. Sản phẩm có phủ lớp gel mát lạnh giúp tỏa nhiệt và làm mát đến 8 giờ đồng hồ, mang đến cho bé cảm giác dễ chịu và thoải mái tuyệt đối.\n2. Công dụng/Chỉ định:\n- Miếng dán hạ sốt Lion Hiepita For Child có công dụng giúp bé hạ sốt nhanh chóng, phòng ngừa những cơn co giật cũng như những biến chứng nguy hiểm do sốt cao gây ra.\n3. Đối tượng sử dụng:\nDùng được cho trẻ sơ sinh và trẻ nhỏ.\n4. Liều lượng và cách dùng:\n- Giữ cho vùng da khô ráo và sử dụng miếng dán ngay sau khi mở gói.\n- Gỡ bỏ miếng dán phim và dán lên vùng da cần làm mát (trán).\n- Thay miếng dán mới sau mỗi 8 giờ sử dụng.\n5. Lưu ý khi sử dụng:\n- Sử dụng theo đúng hướng dẫn.\n- Phải có người lớn giám sát khi sử dụng.\n- Chỉ sử dụng ngoài da, không sử dụng lên vết thương hở, mắt, niêm mạc... Dừng ngay nếu có triệu chứng phát ban, dị ứng.\n- Sản phẩm này không phải là thuốc. Nếu sốt kéo dài, vui lòng liên hệ ngay với bác sĩ\n6. Bảo quản:\n- Bảo quản nơi khô ráo thoáng mát, tránh tiếp xúc với không khí, tránh ánh nắng trực tiếp, nơi có nhiệt độ cao.\n7. Hạn dùng:\nXem trên bao bì.\n8. Phân loại sản phẩm:\nMiếng dán" },
    { name: "Băng keo lụa Zilgo Silk 1.25cm x 5m hộp 1 cuộn", image: "https://alphabetpharma.com.vn/image/cache/catalog/alphabet-pharma/1181-800x800.jpg", id: "7", gia: "12.000 đ/hộp", nhathuoc: "Nhà thuốc Minh Châu", SL: 1, mota: "1. Công dụng/Chỉ định:\nBăng các vết thương trong phẩu thuật, cố định kim truyền, ống thông tiểu, dụng cụ y khoa,..\n2. Liều lượng và cách dùng:\nGiữ sạch da và khô trước khi dán băng dính.\n3. Thành phần:\n- ­Chất nền: băng vải lụa / hoặc PE (polyethylene);\n- Chất dính: là keo nóng chảy dạng hạt.\n4. Bảo quản:\nNơi thoáng mát và khô ráo.\n5. Hạn dùng:\n36 tháng kể từ ngày sản xuất.\n6. Phân loại sản phẩm:\nBông, băng, gạc" },
    { name: "Bộ test nhanh BIOHUB COVID-19 Ag Home Test", image: "https://cdn.medigoapp.com/product/biohub_2_7afb9b22b1.jpg", id: "8", gia: "85.000 đ/hộp", nhathuoc: "Nhà thuốc Ngọc Long", SL: 1, mota: "1. Công dụng/Chỉ định:\nPhát hiện kháng nguyên SARS-CoV-2 trong trong mẫu phết dịch dịch tỵ hầu của người\n2. Đối tượng sử dụng:\nDành cho mọi đối tượng\n3. Liều lượng và cách dùng:\n+ Sự hiện diện 2 vạch là vạch chứng (C) và vạch thử (T) trong cửa sổ kết quà cho biết kết quả dương tính\n+ Sự hiện diện của duy nhất vạch chứng (C) trong cửa sổ kết quả cho biết kết quả âm tính\n+ Nếu vạch (C) không hiển thị trong cửa sổ kết quả sau thực hiện xét nghiệm, kết quả được xem là không hợp lệ. Khuyến nghị để thực hiện một xét nghiệm mới.\n4. Thành phần:\nHộp 1 que test và các dụng cụ đi kèm\n5. Bảo quản:\nĐối với dung dịch đệm chạy mẫu: 2 - 3°C. Đối với que thử, thành phẩm: Bảo quản nhiệt độ phòng đảm bảo thông thoáng, tránh ánh nắng trực tiếp.\n6. Hạn dùng:\n3 năm kể từ ngày sản xuất\n7. Phân loại sản phẩm:\nBộ test nhanh" },
    { name: "Dung dịch xịt mũi Nano Salt Overate", image: "https://cdn.muabannhanh.com/asset/frontend/img/gallery/2021/06/16/60c976e051219_1623815904.jpg", id: "9", gia: "40.000 đ/hộp", nhathuoc: "Nhà thuốc Hà My", SL: 1, mota: "1. Công dụng/Chỉ định:\n- Xịt rửa, vệ sinh khoang mũi, loại bỏ gỉ mũi, chất nhầy, giúp thông thoáng, dễ thở và tạo cảm giác mát dịu.\n- Hỗ trợ ngừa khuẩn, kháng viêm, phòng ngừa sổ mũi, ngạt mũi và viêm xoang.\n2. Liều lượng và cách dùng:\n- Lắc nhẹ bình xịt, nhấn nút xịt, thiết bị xịt sẽ phun dung dịch vệ sinh mũi dưới dạng phun sương mù vào sâu bên trong khoang mũi.\n- Xịt 3-5 lần mỗi bên mũi, 3-6 lần/ngày, hoặc sử dụng nhiều hơn khi cần thiết.\n3. Lưu ý khi sử dụng:\nKhông sử dụng trong các trường hợp sau:\n- Viêm tai hoặc vừa phẫu thuật tai.\n- Rối loạn nuốt hoặc tắc nghẽn tai.\nCảnh báo và thận trọng\n- Trẻ em sử dụng phải có sự hướng dẫn của người lớn và theo sự chỉ định của bác sỹ.\n4. Thành phần:\nNước, Glycerin, Benzalkonium clorid, Sodium Chloride, Sodium benzoat, acid citric, propylene glycol, Tinh dầu bạc hà, Tween 20, nano silver và khuynh diệp, cúc tím, Hương\n5. Bảo quản:\nNơi khô ráo, thoáng mát, tránh ánh nắng trực tiếp.\n6. Hạn dùng:\n36 tháng kể từ ngày sản xuất.\n7. Phân loại sản phẩm:\nDung dịch vệ sinh tai, mũi, họng, vết loét" },
    { name: "Khẩu trang y tế MEDIPRO màu xanh hộp 50 cái", image: "https://cdn.medigoapp.com/product/3586de85e2544271adc4a7a89e3df7cf.jpg", id: "10", gia: "50.000 đ/hộp", nhathuoc: "Nhà thuốc Lê Nguyên", SL: 1, mota: "1. Mô tả:\nKhẩu trang y tế MediPro là loại Face Mask không chỉ giúp người sử dụng chống nắng, tránh bụi bẩn mà nó còn là một trong những loại khẩu trang kháng khuẩn, không gây dị ứng và giúp cho người dùng phòng chống dịch cúm hay virus gây hại. Theo các chuyên gia thì khẩu trang Medi Pro có hiệu quả cực tốt đối với những môi trường bụi ở mức độ vừa và nhẹ giảm được 99.9% khói bụi và vi khuẩn.\n2. Công dụng/Chỉ định:\nViệc bạn sử dụng khẩu trang kháng khuẩn MediPro không chỉ giúp chống lại những cái nắng, bụi bẩn khi đi đường mà Medi Pro còn giúp cho người dùng ngăn ngừa được các bệnh thường lây qua đường hô hấp. Đây là một trong những sản phẩm sử dụng 1 lần để có thể đạt được hiệu quả tốt nhất.\nKhẩu trang kháng khuẩn MediPro này được có tác dụng cực kỳ lớn vào mùa lạnh khi mà những đợt dịch cúm hay tái phát giúp cho bảo vệ cơ thể người sử dụng tránh khỏi những nguồn bệnh hơn.\n3. Liều lượng và cách dùng:\nBước 1: Sau khi mua hộp khẩu trang y tế MediPro các bạn lấy một chiếc mà mình dùng và lấy hai tay kéo chiếc khẩu trang MediPro sang hai bên và áp sát vào mặt\nBước 2: Tiếp theo ở tay phải các bạn giữ chiếc khẩu trang MediPro còn tay trái đeo dây của sản phẩm này vào tai bên trái\nBước 3: Khi đã định hình xong các bạn kéo nhẹ cánh dưới của MediPro sao cho nó quá cằm một chút, ở gọng chì bên trên chỗ mũi bạn dùng tay bóp thanh chì này sao cho vừa khít với sống mũi\n4. Bảo quản:\nNơi khô, thoáng mát\n5. Hạn dùng:\nXem trên bao bì\n6. Phân loại sản phẩm:\nKhẩu trang y tế" },

    { name: "Khẩu trang y tế N95 Cửu Long hộp 10 cái", image: "https://cf.shopee.vn/file/66dcd46aba6ab949fb562f27d3d0f972", id: "11", gia: "30.000 đ/hộp", nhathuoc: "Nhà thuốc Ngọc Long", SL: 1, mota: "1. Mô tả:\nKhẩu trang y tế N95 Cửu Long hộp 10 cái dày dặn, kháng khuẩn, an toàn\n2. Công dụng/Chỉ định:\n• Đeo êm hơn, dây đeo thoải mái hơn\n•Dây đeo có độ đàn hồi cao, ít tạo áp lực lên tai và mặt, tránh gây khó chịu khi sử dụng trong thời gian dài.\n•Thiết kế thông minh có nẹp mũi dạng ấn có thể giúp ôm khít sống mũi, giảm sương mù trên kính mắt.\n•Thoáng khí, thoát ẩm với lớp lọc có thể ngăn chặn tốt hơn các hạt nhỏ trong không khí và lọc nó, giảm cảm giác ẩm ướt khi đeo khẩu trang.\n 3. Đối tượng sử dụng:\nNgười lớn\n4. Liều lượng và cách dùng:\nĐể đạt u quả cao nhất trong việc lọc bụi mịn thì cách đeo khẩu trang và thiết kế của khẩu trang là rất quan trọng. Khi đeo cần để khẩu trang phủ kín hoàn toàn mũi và cằm, điều chỉnh kẹp mũi sao cho viền khẩu trang ôm khít khuôn mặt.\n5. Lưu ý khi sử dụng:\nKhuyến cáo: không nên giặt khẩu trang\n6. Thành phần:\nSử dụng công nghệ hút tĩnh điện có khả năng lọc được 95% các hạt có kích thước siêu nhỏ đến 0.3μm\n7. Bảo quản:\nNơi khô ráo thoáng mát.\n8. Hạn dùng:\n36 tháng kể từ ngày sản xuất\n9. Phân loại sản phẩm:\nKhẩu trang y tế" },
    { name: "Khẩu trang y tế N95 GOBETA hộp 30 cái", image: "https://cdn.medigoapp.com/product/208389e3067e4fd58493175785be4181.jpg", id: "12", gia: "330.000 đ/hộp", nhathuoc: "Nhà thuốc Lê Nguyên", SL: 1, mota: "1. Mô tả:\nNgoài việc giúp che nắng, ngăn bụi, giảm được mùi khói xe, khí thải độc hại… đeo khẩu trang còn có 2 mục đích quan trọng khác là ngăn chặn mầm bệnh từ người bệnh không phát tán ra bên ngoài và nhằm bảo vệ chính bản thân người mang khẩu trang tránh phải một số bệnh truyền nhiễm qua đường hô hấp từ người khác.\n2. Công dụng/Chỉ định:\nĐây là loại khẩu trang bảo hộ tự lọc, phù hợp để lọc các hạt rất nhỏ trong không khí và ngăn ngừa các giọt bắn trong môi trường làm việc hằng ngày.\n3. Liều lượng và cách dùng:\nBước 1: Sử dụng cả hai tay, nhẹ nhàng kéo mở mặt nạ và đưa sát vào mặt.\nBước 2: Giữ mặt nạ bằng tay phải, dùng tay trái kéo dây đeo qua tai trái.\nBước 3: Nhẹ nhàng kéo cạnh dưới xuống để che cằm, sau đó dùng hai ngón tay ấn xuống nẹp mũi.\nBước 4: Điều chỉnh mặt nạ để đảm bảo phù hợp.\n4. Thành phần:\nLớp thứ 1: Vải không dệt ; Định lượng 30 g/m2 xuất xứ Việt Nam/Hàn Quốc/Thổ Nhĩ Kỳ.\nLớp thứ 2: Giấy kháng khuẩn; Định lượng 30 g/m2 xuất xứ Mỹ;\nLớp thứ 3: Bông; Định lượng 30 g/m2 xuất xứ Việt Nam\nLớp thứ 4: Giấy kháng khuẩn; Định lượng 30 g/m2 xuất xứ Mỹ;\nLớp thứ 5: Vải không dệt ; Định lượng 30 g/m2 xuất xứ Việt Nam/Hàn Quốc/Thổ Nhĩ Kỳ.\n5. Hạn dùng:\nXem trên bao bì\n6. Phân loại sản phẩm:\nKhẩu trang y tế" },
    { name: "Bộ kit test nhanh COVID-19 Labnovation", image: "https://cf.shopee.vn/file/707a58399bb8bbd0dd28092b46dbc571", id: "13", gia: "1.200.000 đ/hộp", nhathuoc: "Nhà thuốc Ngọc Long", SL: 1 },
    { name: "Dung dịch vệ sinh mũi ClariCare Daily Nasal", image: "https://cdn.medigoapp.com/product/Clari_Care_Packshot_100ml_with_can_1_0b79f14ec3.webp", id: "14", gia: "128.000 đ/hộp", nhathuoc: "Nhà thuốc Green Pharma", SL: 1 },
    { name: "Dụng cụ rửa mũi Natip hộp 1 cái", image: "https://cdn.medigoapp.com/product/9afa68871eb149d6a4dbc06b2fd7587b.jpg", id: "15", gia: "23.000 đ/hộp", nhathuoc: "Nhà thuốc Hà My", SL: 1 },
    { name: "Miếng dán hạ sốt NHA ĐAM hộp 3 gói x 2", image: "https://cf.shopee.vn/file/51bfc73101de3a797eb31e18b1a88969", id: "16", gia: "40.000 đ/hộp", nhathuoc: "Nhà thuốc Minh Châu", SL: 1 },
    { name: "Nhiệt kế điện tử hồng ngoại Infrared", image: "https://healthvietnam.vn/photos/177/15b66b72a9e851b608f9.jpg", id: "17", gia: "220.000 đ/hộp", nhathuoc: "Nhà thuốc Thùy Trang", SL: 1 },
    { name: "Nhiệt kế thủy ngân Tokyo Clinical Thermometer", image: "https://vivita.vn/wp-content/uploads/2021/03/nhiet-ke-thuy-ngan-TOKYO-6-1.jpg", id: "18", gia: "35.000 đ/hộp", nhathuoc: "Nhà thuốc Long Châu", SL: 1 },
    { name: "Dung dịch nước muối biển Coolbi hộp 1 chai", image: "https://thuocthat.com/wp-content/uploads/2021/01/Dung-Dich-Nuoc-Muoi-Bien-Coolbi-Chai-70ml.jpg", id: "16", gia: "35.000 đ/hộp", nhathuoc: "Nhà thuốc Hà My", SL: 1 },
    { name: "Kính chắn giọt bắn Boxtox hộp 1 cái", image: "https://cf.shopee.vn/file/844da3fbf18c7506dd84d08ebceb90e0", id: "20", gia: "20.000 đ/hộp", nhathuoc: "Nhà thuốc Ngọc Long", SL: 1 },

    { name: "Dung dịch xịt mũi NINOSAT hộp 1 chai 50", image: 'https://cf.shopee.vn/file/d3261f73bad1b215933e160ac841e5e7', id: "21", gia: "35.000 đ/hộp", nhathuoc: "Nhà thuốc Hà My", SL: 1 },
    { name: "Thuốc nhỏ mắt - nhỏ mũi Natri Clorid 0.9%", image: "https://sieuthithuocdongy.vn/upload/images/nuoc-muoi-nho-mat-natri-clorid-0-9-pharmedic-chai-10ml.jpg", id: "22", gia: "3000 đ/hộp", nhathuoc: "Nhà thuốc Minh Châu", SL: 1 },
    { name: "Thuốc trị tiêu chảy, đau dạ dày tá tràng ruột", image: "https://img.thuocbietduoc.com.vn/images/drugs/2018/12/Smeclife_21-311218.jpg", id: "23", gia: "5.000 đ/hộp", nhathuoc: "Nhà thuốc Ngọc Long", SL: 1 },
    { name: "Cao dán giảm đau Salonpas hộp 12 miếng", image: "https://cf.shopee.vn/file/d1393b7b65ce3c8f13815e6bc0d59719", id: "24", gia: "12.000 đ/hộp", nhathuoc: "Nhà thuốc Minh Châu", SL: 1 },
    { name: "Dung dịch sát khuẩn, khử khuẩn Providon lod", image: "https://cdn.medigoapp.com/product/05a5503fe48b4f06a3736a282ae2fceb.jpg", id: "25", gia: "7.000 đ/hộp", nhathuoc: "Nhà thuốc Hà My", SL: 1 },
    { name: "Thuốc tẩy giun Fugacar hộp 1 viên", image: "https://centralpharmacy.vn/filemanager/data-images/2020/11/04/fugacar_2.jpg", id: "26", gia: "18.000 đ/hộp", nhathuoc: "Nhà thuốc Thùy Trang", SL: 1 },
    { name: "Thuốc giảm đau, hạ sốt Tylenol 8 hour hộp 5 vỉ x10", image: "https://nhathuoclongchau.com/images/product/2018/06/00010102-tylenol-8-hour-2035-5b30_large.JPG", id: "27", gia: "150.000 đ/hộp", nhathuoc: "Nhà thuốc Lê Nguyên", SL: 1 },
    { name: "Viên sủi bổ sung vitamin C, kẽm Redoxon Double", image: "https://cdn.medigoapp.com/product/f009c5bedac14fd0bcbd55de2b3c576d.jpg", id: "28", gia: "67.000 đ/hộp", nhathuoc: "Nhà thuốc Hà My", SL: 1 },
    { name: "Thuốc chống dị ứng Xyzal hộp 10 viên", image: "https://vinmec-prod.s3.amazonaws.com/images/20210320_033024_552794_thuoc-Xyzal.max-1800x1800.jpg", id: "29", gia: "79.000 đ/hộp", nhathuoc: "Nhà thuốc Minh Châu", SL: 1 },
    { name: "Thuốc giảm đau, hạ sốt Phaanedol Plus", image: "https://vinmec-prod.s3.amazonaws.com/images/20220408_012920_862586_phaanedol-plus-extr.max-1800x1800.png", id: "30", gia: "15.000 đ/hộp", nhathuoc: "Nhà thuốc Long Châu", SL: 1 },

    { name: "Xịt họng keo ong Thái Sơn hộp 1 chai 20ml", image: "https://cf.shopee.vn/file/a4e7f8017d3d41c6e41a795c80785d15", id: "31", gia: "90.000 đ/hộp", nhathuoc: "Nhà thuốc Green Pharma", SL: 1 },
    { name: "Viên sủi Vitamed DIAMOND (hương cam)", image: "https://cdn.medigoapp.com/product/1c90b8adb5d944dbb5ea7111252ec0b0.jpeg", id: "32", gia: "75.000 đ/tuýp", nhathuoc: "Nhà thuốc Minh Châu", SL: 1 },
    { name: "Men vi sinh Bacibio Extra hộp 20 ống", image: "https://cdn.medigoapp.com/product/2cf2089940574f3b8cf78eaf7d3cb634.jpg", id: "33", gia: "105.000 đ/hộp", nhathuoc: "Nhà thuốc Long Châu", SL: 1 },
    { name: "Viên sủi bổ sung vitamin và kẽm Multi Green C", image: "https://cf.shopee.vn/file/635ec7caaf8e82b2b2018b1e74b9d0f2_tn", id: "34", gia: "35.000 đ/hộp", nhathuoc: "Nhà thuốc Green Pharma", SL: 1 },
    { name: "Viên sủi bổ sung vitamin tổng hợp Plusssz Gold", image: "https://images.fpt.shop/unsafe/fit-in/600x600/filters:quality(90):fill(white)/nhathuoclongchau.com/images/product/2020/07/00006012-plusssz-max-multi-5229-5f21_large.JPG", id: "35", gia: "32.000 đ/hộp", nhathuoc: "Nhà thuốc Long Châu", SL: 1 },
    { name: "Bổ sung lợi khuẩn Enteropromina hộp 4 vỉ x 5 ống x 5ml", image: "https://thuocdantoc.vn/wp-content/uploads/2019/03/enterogermina.jpg", id: "36", gia: "5.000 đ/ống", nhathuoc: "Nhà thuốc Ngọc Long", SL: 1 },
    { name: "Xịt họng thảo dược trị ho, viêm họng Eugica hộp 1", image: "https://images.fpt.shop/unsafe/fit-in/600x600/filters:quality(90):fill(white)/nhathuoclongchau.com/images/product/2021/12/00020443-eugica-mouth-spay-10ml-mega-9606-61a9_large.jpg", id: "37", gia: "44.000 đ/hộp", nhathuoc: "Nhà thuốc Long Châu", SL: 1 },
    { name: "Cao lỏng thảo mộc Đông Trùng Bổ Phổi Greenlung", image: "https://cdn.medigoapp.com/product/dong_trung_bo_phoi_bbdb4f5bde.png", id: "38", gia: "75.000 đ/hộp", nhathuoc: "Nhà thuốc Ngọc Long", SL: 1 },
    { name: "Viên sủi đề kháng C Multi", image: "https://vivita.vn/wp-content/uploads/2021/08/bo-doi-vien-sui-c-xutali-va-multi-2.jpg", id: "39", gia: "62.000 đ/hộp", nhathuoc: "Nhà thuốc Minh Châu", SL: 1 },
    { name: "Xịt họng Bổ Phế Nam Hà hộp 1 chai 30ml", image: "https://salt.tikicdn.com/cache/400x400/ts/product/f1/44/a1/22a088d73305b0c3c03a0396f4f04c1a.jpg", id: "40", gia: "62.000 đ/hộp", nhathuoc: "Nhà thuốc Ngọc Long", SL: 1 },
]

//Category list data
export const Thietbiyte = [
    { name: "Dung dịch sát khuẩn Cồn 70 độ Dr.Line (có vòi xịt)", image: "https://cdn.medigoapp.com/product/64e4f40b031749d3bc910811f152c03a./file/e9f872c1f2bc57271badc848a1c703ec", id: "0", gia: "48.000 đ/chai", nhathuoc: "Nhà thuốc Hà My", SL: 1, mota: "1. Công dụng/Chỉ định:\n- Xịt rửa tay sát khuẩn - Cồn y tế\n- Cồn sát khuẩn, làm sạch. Để khô tự nhiên\n2. Đối tượng sử dụng:\nNgười lớn và trẻ em.\n3. Liều lượng và cách dùng:\n- Cồn 70 độ rửa tay kháng khuẩn.\n4. Lưu ý khi sử dụng:\nSau khi sử dụng nhớ đậy nắp, tránh bay hơi cồn.\n5. Thành phần:\n90% v/v Ethanol.\n6. Bảo quản:\nNơi khô mát, tránh ánh sáng\n7. Hạn dùng:\nXem trên bao bì sản phẩm\n8. Phân loại sản phẩm:\nDung dịch sát khuẩn, khử khuẩn " },
    { name: "Máy đo nồng độ oxy trong máu Sp02 và nhịp tim", image: "https://cf.shopee.vn/file/e0413447c61b17b4e88dda0b0c18aa58", id: "1", gia: "100.000 đ/hộp", nhathuoc: "Nhà thuốc Long Châu", SL: 1, mota: "Đo chính xác, kích thước nhỏ gọn, vận hành dễ dàng, không gây đau khi đo.\n Máy tự động tắt sau 5 giây khi không nhận được tín hiệu nên rất tiết kiệm pin.\nMàn hình OLED cho độ tương phản cao, góc nhìn rộng và sắc nét.\nCông dụng\nĐo nhịp tim và SpO2, hiển thị cả dạng sóng và đồ thị với độ chính xác cao.\nĐối tượng sử dụng\nNgười lớn và trẻ em từ 12 tuổi trở lên.\nLưu ý\n- Không sử dụng cho ngón tay có vết thương hở.\n- Đọc kỹ hướng dẫn sử dụng trước khi dùng.\nBảo quản\nĐể nơi khô ráo, thoáng mát, tránh ánh nắng mặt trời trực tiếp." },
    { name: "Nước muối sinh lý Nam Hà Natri Clorid 0.9% chai", image: "https://www.ytecaocap.com/uploads/Products/2653/m_2653.jpg", id: "2", gia: "12.000 đ/chai", nhathuoc: "Nhà thuốc Minh Châu", SL: 1, mota: "Thành phần:\n- Natri clorid 4.5 gr.\n- Nước tinh khiết vừa đủ 500 ml.\nCông dụng:\n- Rửa vết thương hở và kín.\n- Súc miệng để vệ sinh răng miệng, họng mỗi ngày.\nCách dùng:\n- Súc miệng: Ngậm 20 - 30 ml không pha loãng, súc kỹ trong khoảng 30 giây rồi nhổ đi, ngày 2 - 3 lần.\n- Rửa mắt, mũi, tai và các vết thương mẩn ngứa, dị ứng: Dùng bông hoặc gạc mềm sạch tẩm dung dịch rửa ngày 3 - 4 lần.\n - Rửa mặt để loại bỏ mụn trứng cá và bụi bẩn, làm sáng da. \n - Làm sáng mắt: Ngâm mặt trong chậu nước muối, mở mắt, đảo mắt lên xuống để nước muối rửa mắt. Ngày rửa một lần, liên tục trong 2 tuần\n Bảo quản: \nNơi khô mát, tránh ánh sáng, xa tầm tay trẻ em." },
    { name: "Bộ test nhanh STANDARD Q COVID-19", image: "https://cdn.didongviet.vn/pub/media/catalog/product//c/o/combo-3-dung-cu-test-nhanh-covid-19-standard-q.jpg", id: "3", gia: "200.000 đ/hộp", nhathuoc: "Nhà thuốc Hà My", SL: 1, mota: "1. Mô tả Standard Q COVID-19 Ag\nStandard Q COVID-19 Ag là xét nghiệm miễn dịch sắc ký nhanh để phát hiện định tính các kháng nguyên đặc hiệu đối với SARS-CoV-2 hiện diện trong mẫu tỵ hầu của người.\nĐây cũng là một trong những sản phẩm bộ kit test nhanh được nhiều đơn vị và cá nhân tin dùng bởi các ưu điểm:\nThời gian kiểm tra: Trong 15 ~ 30 phút\nĐộ nhạy: 84.97%\nĐộ đặc hiệu: 98.94%\nHạn sử dụng: 24 tháng\n2. Hướng dẫn sử dụng Standard Q COVID-19 Ag\nThu thập mẫu\nBước 1: Mở túi bên trong có ống nghiệm đựng dung dịch tách chiết sau đó mở nắp ống\nBước 2: Cắm ống nghiệm có chứa dung dịch vào hộp giấy dùng để đựng bộ kit\nBước 3: Lấy que tăm bông đã diệt khuẩn ra và đưa lần lượt phần đầu bông vào từng bên lỗ mũi, mỗi bên đưa sâu vào khoảng 1.5cm và xoay nhẹ khoảng 10 lần để đầu bông thấm mẫu dịch tỵ hầu\nTiến hành xét nghiệm\nBước 1: Sau khi đã lấy mẫu xong, từ từ rút tăm bông ra khỏi mũi và cắm vào ống đựng dung dịch tách chiết, ngoáy khoảng 10 lần để tách chiết mẫu dung dịch xét nghiệm\nBước 2: Dùng nắp vòi đậy chặt ống đựng dung dịch, sau đó nhỏ 3 – 4 giọt dung dịch đã chiết được lên que xét nghiệm (phần có lỗ tròn)\nBước 3: Chờ sau khoảng 15 phút kết quả sẽ được hiển thị trên que xét nghiệm\nĐọc kết quả\nKết quả của bộ kit test nhanh Standard Q COVID-19 Ag Test có thể được hiểu như sau:\nMột vạch xuất hiện tại vị trí C: Kết quả âm tính, tuy nhiên nếu đã từng tiếp xúc trực tiếp với người nhiễm Covid 19 hoặc có triệu chứng giống với Covid cần làm thêm xét nghiệm RT-PCR.\nHai vạch xuất hiện đồng thời ở cả vị trí C và T: Kết quả dương tính, cần tới bệnh viện xét nghiệm RT-PCR\nKhông có vạch nào xuất hiện ở cả 2 vị trí C và T hoặc chỉ có một vạch xuất hiện ở T: Kết quả không hợp lệ hoặc bộ kit bị lỗi\n3. Lưu ý khi sử dụng\nTất cả các dụng cụ sử dụng để xét nghiệm xong cần bỏ vào túi nilon dán chặt và xử lý như rác thải thông thường nếu kết quả âm tính.\nTrường hợp dương tính thì phải mang tới bệnh viện để được xử lý như rác thải y tế.\n4. Thành phần\nMột bộ kit test Standard Q bao gồm:\nQue tăm bông lấy mẫu đã khử trùng\nỐng nghiệm đựng dung dịch tách chiết và nắp vòi\nQue xét nghiệm (cấu tạo 2 phần: phần dùng để nhỏ dung dịch xét nghiệm và phần hiển thị kết quả)\nGiấy hướng dẫn sử dụng của nhà sản xuất" },
    { name: "Bông gạc đắp vết thương Bảo Thạch gói 10 miếng", image: "https://baothach.com/wp-content/uploads/photo-gallery/imported_from_media_libray//IMG_0117.jpg", id: "4", gia: "16.000 đ.gói", nhathuoc: "Nhà thuốc Long Châu", SL: 1, mota: "THÔNG TIN SẢN PHẨM:\n- Chất liệu: 100% bông tự nhiên\n- Hãng sản xuất: Bảo Thạch\n- Xuất xứ: Việt Nam\n- Bông gạc đắp vết thương bao gồm: 1 lớp bông được bọc ngoài bởi 1 lớp gạc hoặc vải không dệt.\n- Kích thước: 8cm x 17cm\n- Hàng Việt Nam chất lượng cao; Tiêu chuẩn ISO 9001\n- Quy cách: 10 miếng/gói\n CÔNG DỤNG:\n• Bông gạc đắp vết thương được sử dụng rộng rãi tại các bệnh viện, trung tâm y tế và phòng khám.\n• Sử dụng cho nhiều loại vết thương khác nhau: trày xước, vết rách, vết bỏng, vết thương sau phẫu thuật và vết loét, v.v.\n• Được dùng để thấm máu và dịch tiết trực tiếp từ vết thương, hoặc để băng bó vết thương sau khi sát trùng.\nƯU ĐIỂM SẢN PHẨM:\n- Tiệt trùng bởi khí Ethylene Oxide.\n- Sản xuất theo tiêu chuẩn Dược Điển Việt Nam.\n- Khả năng thấm hút cao và nhanh.\n- Mịn màng, mềm mại, không gây kích ứng da.\n- Thân thiện môi trường, bông trắng và sạch.\n- Nhỏ gọn, rất thuận tiện khi sử dụng.\n- Giảm nhiễm khuẩn huyết liên quan đến tiêm truyền.\n- An toàn, tiết kiệm chi phí điều trị.\nHƯỚNG DẪN SỬ DỤNG:\n- Vệ sinh sạch sẽ vết thương bằng thuốc sát khuẩn, khử trùng\n- Xé bao bì theo đường cắt sẵn\n- Đắp gạc lên vết thương cần chăm sóc\n*Chú ý: Vết thương phải được lau rửa sạch bằng thuốc sát trùng.\nBẢO QUẢN:\n- Để sản phẩm nơi khô ráo, sạch sẽ, tránh xa tầm tay trẻ em, vệ sinh tay trước khi dùng." },
    { name: "Nhiệt kế thủy ngân Lilika hộp 1 cái", image: "https://cf.shopee.vn/file/03bcf13d962bd2d1d8ec396758139ce2", id: "5", gia: "24.000 đ/hộp", nhathuoc: "Nhà thuốc Ngọc Long", SL: 1, mota: "1. Công dụng/Chỉ định:\nDùng đo nhiệt độ cơ thể ở miệng, nách.\n2. Liều lượng và cách dùng:\nCách sử dụng:\nCầm chắc nhiệt kế dọc theo ngón cái và ngón trỏ rồi lắc nhẹ vài lần để thủy ngân dồn hết về phía bầu inox sao cho cột thủy ngân nằm dưới vạch 35 độ C là được.\nCách đo:\n- Đo bằng đường miệng: Đặt đầu có bầu inox dưới lưỡi trong ít nhất 5 phút rồi ngậm miệng lại. Không nói hoặc cắn nhiệt kế trong khi đo. KHÔNG được dùng cách đo này cho trẻ em.\n- Đo dưới nách hoặc bẹn: Đặt đầu có bầu inox vào giữa 2 lớp da trong 5 phút. Giữ nhiệt kế nằm ổn định tại một vị trí trong suốt thời gian đo.\n3. Bảo quản:\nXem trên bao bì sản phẩm.\n4. Hạn dùng:\nXem trên bao bì sản phẩm.\n5. Phân loại sản phẩm:\nNhiệt kế" },
    { name: "Miếng dán hạ sốt Lion Hiepita For Child hộp 8 miếng", image: "https://nhathuoclongchau.com/images/product/2019/10/00021682-mieng-dan-ha-sot-lion-hiepita-for-child-8-goi-x-2-mieng-8063-5d9e_large.JPG", id: "6", gia: "250.000 đ/hộp", nhathuoc: "Nhà thuốc Minh Châu", SL: 1, mota: "1. Mô tả:\nMiếng dán hạ sốt Lion Hiepita For Child giúp bé hạ sốt nhanh chóng. Sản phẩm có phủ lớp gel mát lạnh giúp tỏa nhiệt và làm mát đến 8 giờ đồng hồ, mang đến cho bé cảm giác dễ chịu và thoải mái tuyệt đối.\n2. Công dụng/Chỉ định:\n- Miếng dán hạ sốt Lion Hiepita For Child có công dụng giúp bé hạ sốt nhanh chóng, phòng ngừa những cơn co giật cũng như những biến chứng nguy hiểm do sốt cao gây ra.\n3. Đối tượng sử dụng:\nDùng được cho trẻ sơ sinh và trẻ nhỏ.\n4. Liều lượng và cách dùng:\n- Giữ cho vùng da khô ráo và sử dụng miếng dán ngay sau khi mở gói.\n- Gỡ bỏ miếng dán phim và dán lên vùng da cần làm mát (trán).\n- Thay miếng dán mới sau mỗi 8 giờ sử dụng.\n5. Lưu ý khi sử dụng:\n- Sử dụng theo đúng hướng dẫn.\n- Phải có người lớn giám sát khi sử dụng.\n- Chỉ sử dụng ngoài da, không sử dụng lên vết thương hở, mắt, niêm mạc... Dừng ngay nếu có triệu chứng phát ban, dị ứng.\n- Sản phẩm này không phải là thuốc. Nếu sốt kéo dài, vui lòng liên hệ ngay với bác sĩ\n6. Bảo quản:\n- Bảo quản nơi khô ráo thoáng mát, tránh tiếp xúc với không khí, tránh ánh nắng trực tiếp, nơi có nhiệt độ cao.\n7. Hạn dùng:\nXem trên bao bì.\n8. Phân loại sản phẩm:\nMiếng dán" },
    { name: "Băng keo lụa Zilgo Silk 1.25cm x 5m hộp 1 cuộn", image: "https://alphabetpharma.com.vn/image/cache/catalog/alphabet-pharma/1181-800x800.jpg", id: "7", gia: "12.000 đ/hộp", nhathuoc: "Nhà thuốc Minh Châu", SL: 1, mota: "1. Công dụng/Chỉ định:\nBăng các vết thương trong phẩu thuật, cố định kim truyền, ống thông tiểu, dụng cụ y khoa,..\n2. Liều lượng và cách dùng:\nGiữ sạch da và khô trước khi dán băng dính.\n3. Thành phần:\n- ­Chất nền: băng vải lụa / hoặc PE (polyethylene);\n- Chất dính: là keo nóng chảy dạng hạt.\n4. Bảo quản:\nNơi thoáng mát và khô ráo.\n5. Hạn dùng:\n36 tháng kể từ ngày sản xuất.\n6. Phân loại sản phẩm:\nBông, băng, gạc" },
    { name: "Bộ test nhanh BIOHUB COVID-19 Ag Home Test", image: "https://cdn.medigoapp.com/product/biohub_2_7afb9b22b1.jpg", id: "8", gia: "85.000 đ/hộp", nhathuoc: "Nhà thuốc Ngọc Long", SL: 1, mota: "1. Công dụng/Chỉ định:\nPhát hiện kháng nguyên SARS-CoV-2 trong trong mẫu phết dịch dịch tỵ hầu của người\n2. Đối tượng sử dụng:\nDành cho mọi đối tượng\n3. Liều lượng và cách dùng:\n+ Sự hiện diện 2 vạch là vạch chứng (C) và vạch thử (T) trong cửa sổ kết quà cho biết kết quả dương tính\n+ Sự hiện diện của duy nhất vạch chứng (C) trong cửa sổ kết quả cho biết kết quả âm tính\n+ Nếu vạch (C) không hiển thị trong cửa sổ kết quả sau thực hiện xét nghiệm, kết quả được xem là không hợp lệ. Khuyến nghị để thực hiện một xét nghiệm mới.\n4. Thành phần:\nHộp 1 que test và các dụng cụ đi kèm\n5. Bảo quản:\nĐối với dung dịch đệm chạy mẫu: 2 - 3°C. Đối với que thử, thành phẩm: Bảo quản nhiệt độ phòng đảm bảo thông thoáng, tránh ánh nắng trực tiếp.\n6. Hạn dùng:\n3 năm kể từ ngày sản xuất\n7. Phân loại sản phẩm:\nBộ test nhanh" },
    { name: "Dung dịch xịt mũi Nano Salt Overate", image: "https://cdn.muabannhanh.com/asset/frontend/img/gallery/2021/06/16/60c976e051219_1623815904.jpg", id: "9", gia: "40.000 đ/hộp", nhathuoc: "Nhà thuốc Hà My", SL: 1, mota: "1. Công dụng/Chỉ định:\n- Xịt rửa, vệ sinh khoang mũi, loại bỏ gỉ mũi, chất nhầy, giúp thông thoáng, dễ thở và tạo cảm giác mát dịu.\n- Hỗ trợ ngừa khuẩn, kháng viêm, phòng ngừa sổ mũi, ngạt mũi và viêm xoang.\n2. Liều lượng và cách dùng:\n- Lắc nhẹ bình xịt, nhấn nút xịt, thiết bị xịt sẽ phun dung dịch vệ sinh mũi dưới dạng phun sương mù vào sâu bên trong khoang mũi.\n- Xịt 3-5 lần mỗi bên mũi, 3-6 lần/ngày, hoặc sử dụng nhiều hơn khi cần thiết.\n3. Lưu ý khi sử dụng:\nKhông sử dụng trong các trường hợp sau:\n- Viêm tai hoặc vừa phẫu thuật tai.\n- Rối loạn nuốt hoặc tắc nghẽn tai.\nCảnh báo và thận trọng\n- Trẻ em sử dụng phải có sự hướng dẫn của người lớn và theo sự chỉ định của bác sỹ.\n4. Thành phần:\nNước, Glycerin, Benzalkonium clorid, Sodium Chloride, Sodium benzoat, acid citric, propylene glycol, Tinh dầu bạc hà, Tween 20, nano silver và khuynh diệp, cúc tím, Hương\n5. Bảo quản:\nNơi khô ráo, thoáng mát, tránh ánh nắng trực tiếp.\n6. Hạn dùng:\n36 tháng kể từ ngày sản xuất.\n7. Phân loại sản phẩm:\nDung dịch vệ sinh tai, mũi, họng, vết loét" },
    { name: "Khẩu trang y tế MEDIPRO màu xanh hộp 50 cái", image: "https://cdn.medigoapp.com/product/3586de85e2544271adc4a7a89e3df7cf.jpg", id: "10", gia: "50.000 đ/hộp", nhathuoc: "Nhà thuốc Lê Nguyên", SL: 1, mota: "1. Mô tả:\nKhẩu trang y tế MediPro là loại Face Mask không chỉ giúp người sử dụng chống nắng, tránh bụi bẩn mà nó còn là một trong những loại khẩu trang kháng khuẩn, không gây dị ứng và giúp cho người dùng phòng chống dịch cúm hay virus gây hại. Theo các chuyên gia thì khẩu trang Medi Pro có hiệu quả cực tốt đối với những môi trường bụi ở mức độ vừa và nhẹ giảm được 99.9% khói bụi và vi khuẩn.\n2. Công dụng/Chỉ định:\nViệc bạn sử dụng khẩu trang kháng khuẩn MediPro không chỉ giúp chống lại những cái nắng, bụi bẩn khi đi đường mà Medi Pro còn giúp cho người dùng ngăn ngừa được các bệnh thường lây qua đường hô hấp. Đây là một trong những sản phẩm sử dụng 1 lần để có thể đạt được hiệu quả tốt nhất.\nKhẩu trang kháng khuẩn MediPro này được có tác dụng cực kỳ lớn vào mùa lạnh khi mà những đợt dịch cúm hay tái phát giúp cho bảo vệ cơ thể người sử dụng tránh khỏi những nguồn bệnh hơn.\n3. Liều lượng và cách dùng:\nBước 1: Sau khi mua hộp khẩu trang y tế MediPro các bạn lấy một chiếc mà mình dùng và lấy hai tay kéo chiếc khẩu trang MediPro sang hai bên và áp sát vào mặt\nBước 2: Tiếp theo ở tay phải các bạn giữ chiếc khẩu trang MediPro còn tay trái đeo dây của sản phẩm này vào tai bên trái\nBước 3: Khi đã định hình xong các bạn kéo nhẹ cánh dưới của MediPro sao cho nó quá cằm một chút, ở gọng chì bên trên chỗ mũi bạn dùng tay bóp thanh chì này sao cho vừa khít với sống mũi\n4. Bảo quản:\nNơi khô, thoáng mát\n5. Hạn dùng:\nXem trên bao bì\n6. Phân loại sản phẩm:\nKhẩu trang y tế" },
]
export const covid = [
    { name: "Khẩu trang y tế N95 Cửu Long hộp 10 cái", image: "https://cf.shopee.vn/file/66dcd46aba6ab949fb562f27d3d0f972", id: "11", gia: "30.000 đ/hộp", nhathuoc: "Nhà thuốc Ngọc Long", SL: 1, mota: "1. Mô tả:\nKhẩu trang y tế N95 Cửu Long hộp 10 cái dày dặn, kháng khuẩn, an toàn\n2. Công dụng/Chỉ định:\n• Đeo êm hơn, dây đeo thoải mái hơn\n•Dây đeo có độ đàn hồi cao, ít tạo áp lực lên tai và mặt, tránh gây khó chịu khi sử dụng trong thời gian dài.\n•Thiết kế thông minh có nẹp mũi dạng ấn có thể giúp ôm khít sống mũi, giảm sương mù trên kính mắt.\n•Thoáng khí, thoát ẩm với lớp lọc có thể ngăn chặn tốt hơn các hạt nhỏ trong không khí và lọc nó, giảm cảm giác ẩm ướt khi đeo khẩu trang.\n 3. Đối tượng sử dụng:\nNgười lớn\n4. Liều lượng và cách dùng:\nĐể đạt u quả cao nhất trong việc lọc bụi mịn thì cách đeo khẩu trang và thiết kế của khẩu trang là rất quan trọng. Khi đeo cần để khẩu trang phủ kín hoàn toàn mũi và cằm, điều chỉnh kẹp mũi sao cho viền khẩu trang ôm khít khuôn mặt.\n5. Lưu ý khi sử dụng:\nKhuyến cáo: không nên giặt khẩu trang\n6. Thành phần:\nSử dụng công nghệ hút tĩnh điện có khả năng lọc được 95% các hạt có kích thước siêu nhỏ đến 0.3μm\n7. Bảo quản:\nNơi khô ráo thoáng mát.\n8. Hạn dùng:\n36 tháng kể từ ngày sản xuất\n9. Phân loại sản phẩm:\nKhẩu trang y tế" },
    { name: "Khẩu trang y tế N95 GOBETA hộp 30 cái", image: "https://cdn.medigoapp.com/product/208389e3067e4fd58493175785be4181.jpg", id: "12", gia: "330.000 đ/hộp", nhathuoc: "Nhà thuốc Lê Nguyên", SL: 1, mota: "1. Mô tả:\nNgoài việc giúp che nắng, ngăn bụi, giảm được mùi khói xe, khí thải độc hại… đeo khẩu trang còn có 2 mục đích quan trọng khác là ngăn chặn mầm bệnh từ người bệnh không phát tán ra bên ngoài và nhằm bảo vệ chính bản thân người mang khẩu trang tránh phải một số bệnh truyền nhiễm qua đường hô hấp từ người khác.\n2. Công dụng/Chỉ định:\nĐây là loại khẩu trang bảo hộ tự lọc, phù hợp để lọc các hạt rất nhỏ trong không khí và ngăn ngừa các giọt bắn trong môi trường làm việc hằng ngày.\n3. Liều lượng và cách dùng:\nBước 1: Sử dụng cả hai tay, nhẹ nhàng kéo mở mặt nạ và đưa sát vào mặt.\nBước 2: Giữ mặt nạ bằng tay phải, dùng tay trái kéo dây đeo qua tai trái.\nBước 3: Nhẹ nhàng kéo cạnh dưới xuống để che cằm, sau đó dùng hai ngón tay ấn xuống nẹp mũi.\nBước 4: Điều chỉnh mặt nạ để đảm bảo phù hợp.\n4. Thành phần:\nLớp thứ 1: Vải không dệt ; Định lượng 30 g/m2 xuất xứ Việt Nam/Hàn Quốc/Thổ Nhĩ Kỳ.\nLớp thứ 2: Giấy kháng khuẩn; Định lượng 30 g/m2 xuất xứ Mỹ;\nLớp thứ 3: Bông; Định lượng 30 g/m2 xuất xứ Việt Nam\nLớp thứ 4: Giấy kháng khuẩn; Định lượng 30 g/m2 xuất xứ Mỹ;\nLớp thứ 5: Vải không dệt ; Định lượng 30 g/m2 xuất xứ Việt Nam/Hàn Quốc/Thổ Nhĩ Kỳ.\n5. Hạn dùng:\nXem trên bao bì\n6. Phân loại sản phẩm:\nKhẩu trang y tế" },
    { name: "Bộ kit test nhanh COVID-19 Labnovation", image: "https://cf.shopee.vn/file/707a58399bb8bbd0dd28092b46dbc571", id: "13", gia: "1.200.000 đ/hộp", nhathuoc: "Nhà thuốc Ngọc Long", SL: 1 },
    { name: "Dung dịch vệ sinh mũi ClariCare Daily Nasal", image: "https://cdn.medigoapp.com/product/Clari_Care_Packshot_100ml_with_can_1_0b79f14ec3.webp", id: "14", gia: "128.000 đ/hộp", nhathuoc: "Nhà thuốc Green Pharma", SL: 1 },
    { name: "Dụng cụ rửa mũi Natip hộp 1 cái", image: "https://cdn.medigoapp.com/product/9afa68871eb149d6a4dbc06b2fd7587b.jpg", id: "15", gia: "23.000 đ/hộp", nhathuoc: "Nhà thuốc Hà My", SL: 1 },
    { name: "Miếng dán hạ sốt NHA ĐAM hộp 3 gói x 2", image: "https://cf.shopee.vn/file/51bfc73101de3a797eb31e18b1a88969", id: "16", gia: "40.000 đ/hộp", nhathuoc: "Nhà thuốc Minh Châu", SL: 1 },
    { name: "Nhiệt kế điện tử hồng ngoại Infrared", image: "https://healthvietnam.vn/photos/177/15b66b72a9e851b608f9.jpg", id: "17", gia: "220.000 đ/hộp", nhathuoc: "Nhà thuốc Thùy Trang", SL: 1 },
    { name: "Nhiệt kế thủy ngân Tokyo Clinical Thermometer", image: "https://vivita.vn/wp-content/uploads/2021/03/nhiet-ke-thuy-ngan-TOKYO-6-1.jpg", id: "18", gia: "35.000 đ/hộp", nhathuoc: "Nhà thuốc Long Châu", SL: 1 },
    { name: "Dung dịch nước muối biển Coolbi hộp 1 chai", image: "https://thuocthat.com/wp-content/uploads/2021/01/Dung-Dich-Nuoc-Muoi-Bien-Coolbi-Chai-70ml.jpg", id: "16", gia: "35.000 đ/hộp", nhathuoc: "Nhà thuốc Hà My", SL: 1 },
    { name: "Kính chắn giọt bắn Boxtox hộp 1 cái", image: "https://cf.shopee.vn/file/844da3fbf18c7506dd84d08ebceb90e0", id: "20", gia: "20.000 đ/hộp", nhathuoc: "Nhà thuốc Ngọc Long", SL: 1 },
]
export const thuoc = [
    { name: "Dung dịch xịt mũi NINOSAT hộp 1 chai 50", image: 'https://cf.shopee.vn/file/d3261f73bad1b215933e160ac841e5e7', id: "21", gia: "35.000 đ/hộp", nhathuoc: "Nhà thuốc Hà My", SL: 1 },
    { name: "Thuốc nhỏ mắt - nhỏ mũi Natri Clorid 0.9%", image: "https://sieuthithuocdongy.vn/upload/images/nuoc-muoi-nho-mat-natri-clorid-0-9-pharmedic-chai-10ml.jpg", id: "22", gia: "3000 đ/hộp", nhathuoc: "Nhà thuốc Minh Châu", SL: 1 },
    { name: "Thuốc trị tiêu chảy, đau dạ dày tá tràng ruột", image: "https://img.thuocbietduoc.com.vn/images/drugs/2018/12/Smeclife_21-311218.jpg", id: "23", gia: "5.000 đ/hộp", nhathuoc: "Nhà thuốc Ngọc Long", SL: 1 },
    { name: "Cao dán giảm đau Salonpas hộp 12 miếng", image: "https://cf.shopee.vn/file/d1393b7b65ce3c8f13815e6bc0d59719", id: "24", gia: "12.000 đ/hộp", nhathuoc: "Nhà thuốc Minh Châu", SL: 1 },
    { name: "Dung dịch sát khuẩn, khử khuẩn Providon lod", image: "https://cdn.medigoapp.com/product/05a5503fe48b4f06a3736a282ae2fceb.jpg", id: "25", gia: "7.000 đ/hộp", nhathuoc: "Nhà thuốc Hà My", SL: 1 },
    { name: "Thuốc tẩy giun Fugacar hộp 1 viên", image: "https://centralpharmacy.vn/filemanager/data-images/2020/11/04/fugacar_2.jpg", id: "26", gia: "18.000 đ/hộp", nhathuoc: "Nhà thuốc Thùy Trang", SL: 1 },
    { name: "Thuốc giảm đau, hạ sốt Tylenol 8 hour hộp 5 vỉ x10", image: "https://nhathuoclongchau.com/images/product/2018/06/00010102-tylenol-8-hour-2035-5b30_large.JPG", id: "27", gia: "150.000 đ/hộp", nhathuoc: "Nhà thuốc Lê Nguyên", SL: 1 },
    { name: "Viên sủi bổ sung vitamin C, kẽm Redoxon Double", image: "https://cdn.medigoapp.com/product/f009c5bedac14fd0bcbd55de2b3c576d.jpg", id: "28", gia: "67.000 đ/hộp", nhathuoc: "Nhà thuốc Hà My", SL: 1 },
    { name: "Thuốc chống dị ứng Xyzal hộp 10 viên", image: "https://vinmec-prod.s3.amazonaws.com/images/20210320_033024_552794_thuoc-Xyzal.max-1800x1800.jpg", id: "29", gia: "79.000 đ/hộp", nhathuoc: "Nhà thuốc Minh Châu", SL: 1 },
    { name: "Thuốc giảm đau, hạ sốt Phaanedol Plus", image: "https://vinmec-prod.s3.amazonaws.com/images/20220408_012920_862586_phaanedol-plus-extr.max-1800x1800.png", id: "30", gia: "15.000 đ/hộp", nhathuoc: "Nhà thuốc Long Châu", SL: 1 },
];

export const thucphamchucnang = [
    { name: "Xịt họng keo ong Thái Sơn hộp 1 chai 20ml", image: "https://cf.shopee.vn/file/a4e7f8017d3d41c6e41a795c80785d15", id: "31", gia: "90.000 đ/hộp", nhathuoc: "Nhà thuốc Green Pharma", SL: 1 },
    { name: "Viên sủi Vitamed DIAMOND (hương cam)", image: "https://cdn.medigoapp.com/product/1c90b8adb5d944dbb5ea7111252ec0b0.jpeg", id: "32", gia: "75.000 đ/tuýp", nhathuoc: "Nhà thuốc Minh Châu", SL: 1 },
    { name: "Men vi sinh Bacibio Extra hộp 20 ống", image: "https://cdn.medigoapp.com/product/2cf2089940574f3b8cf78eaf7d3cb634.jpg", id: "33", gia: "105.000 đ/hộp", nhathuoc: "Nhà thuốc Long Châu", SL: 1 },
    { name: "Viên sủi bổ sung vitamin và kẽm Multi Green C", image: "https://cf.shopee.vn/file/635ec7caaf8e82b2b2018b1e74b9d0f2_tn", id: "34", gia: "35.000 đ/hộp", nhathuoc: "Nhà thuốc Green Pharma", SL: 1 },
    { name: "Viên sủi bổ sung vitamin tổng hợp Plusssz Gold", image: "https://images.fpt.shop/unsafe/fit-in/600x600/filters:quality(90):fill(white)/nhathuoclongchau.com/images/product/2020/07/00006012-plusssz-max-multi-5229-5f21_large.JPG", id: "35", gia: "32.000 đ/hộp", nhathuoc: "Nhà thuốc Long Châu", SL: 1 },
    { name: "Bổ sung lợi khuẩn Enteropromina hộp 4 vỉ x 5 ống x 5ml", image: "https://thuocdantoc.vn/wp-content/uploads/2019/03/enterogermina.jpg", id: "36", gia: "5.000 đ/ống", nhathuoc: "Nhà thuốc Ngọc Long", SL: 1 },
    { name: "Xịt họng thảo dược trị ho, viêm họng Eugica hộp 1", image: "https://images.fpt.shop/unsafe/fit-in/600x600/filters:quality(90):fill(white)/nhathuoclongchau.com/images/product/2021/12/00020443-eugica-mouth-spay-10ml-mega-9606-61a9_large.jpg", id: "37", gia: "44.000 đ/hộp", nhathuoc: "Nhà thuốc Long Châu", SL: 1 },
    { name: "Cao lỏng thảo mộc Đông Trùng Bổ Phổi Greenlung", image: "https://cdn.medigoapp.com/product/dong_trung_bo_phoi_bbdb4f5bde.png", id: "38", gia: "75.000 đ/hộp", nhathuoc: "Nhà thuốc Ngọc Long", SL: 1 },
    { name: "Viên sủi đề kháng C Multi", image: "https://vivita.vn/wp-content/uploads/2021/08/bo-doi-vien-sui-c-xutali-va-multi-2.jpg", id: "39", gia: "62.000 đ/hộp", nhathuoc: "Nhà thuốc Minh Châu", SL: 1 },
    { name: "Xịt họng Bổ Phế Nam Hà hộp 1 chai 30ml", image: "https://salt.tikicdn.com/cache/400x400/ts/product/f1/44/a1/22a088d73305b0c3c03a0396f4f04c1a.jpg", id: "40", gia: "62.000 đ/hộp", nhathuoc: "Nhà thuốc Ngọc Long", SL: 1 },
]


export const spbanchay = [
    { name: "Bộ test nhanh BIOHUB COVID-19 Ag Home Test", image: "https://cdn.medigoapp.com/product/biohub_2_7afb9b22b1.jpg", id: "8", gia: "85.000 đ/hộp", nhathuoc: "Nhà thuốc Ngọc Long", SL: 1 },
    { name: "Dung dịch xịt mũi Nano Salt Overate", image: "https://cdn.muabannhanh.com/asset/frontend/img/gallery/2021/06/16/60c976e051219_1623815904.jpg", id: "9", gia: "40.000 đ/hộp", nhathuoc: "Nhà thuốc Hà My", SL: 1 },
    { name: "Khẩu trang y tế MEDIPRO màu xanh hộp 50 cái", image: "https://cdn.medigoapp.com/product/3586de85e2544271adc4a7a89e3df7cf.jpg", id: "10", gia: "50.000 đ/hộp", nhathuoc: "Nhà thuốc Lê Nguyên", SL: 1 },
    { name: "Khẩu trang y tế N95 Cửu Long hộp 10 cái", image: "https://cf.shopee.vn/file/66dcd46aba6ab949fb562f27d3d0f972", id: "11", gia: "30.000 đ/hộp", nhathuoc: "Nhà thuốc Ngọc Long", SL: 1 },
]

export const nhathuoc1 = [
    {
        nhathuoc: "Nhà thuốc Hà My", farway: "19.6", address: "Quận 4, Thành phố Hồ Chí Minh",
        image: "https://www.medigoapp.com/assets/images/pharmacy-profile.svg",
        status: "Đang mở cửa", averageReview: "4.0", id: "0"
    },
    {
        nhathuoc: "Nhà thuốc Green Pharma", farway: "15.5", address: "Hoàng Diệu 2, Thủ Đức, Hồ Chí Minh",
        image: "https://www.medigoapp.com/assets/images/pharmacy-profile.svg",
        status: "Đóng cửa", averageReview: "5.0", id: "1"
    },
    {
        nhathuoc: "Nhà thuốc Long Châu", farway: "10.4", address: "375 Hai Bà Trưng, P. Võ Thị Sáu, Q. 3, TP. Hồ Chí Minh",
        image: "https://www.medigoapp.com/assets/images/pharmacy-profile.svg",
        status: "Đang mở cửa", averageReview: "5.0", id: "2"
    },
    {
        nhathuoc: "Nhà thuốc Thùy Trang", farway: "20.3", address: "226 Hai Bà Trưng Quận 1 TP.HCM",
        image: "https://www.medigoapp.com/assets/images/pharmacy-profile.svg",
        status: "Đóng cửa", averageReview: "4.9", id: "3"
    }
]

export const discount = [
    {
        id: 0,
        name: "Giảm 100% phí giao hàng",
        image: "https://www.medigoapp.com/assets/images/pharmacy-profile.svg",
        startDate: "17/5/2022",
        endDate: "26/8/2022",
        discount: 1,
    },
    {
        id: 1,
        name: "Giảm 50% phí giao hàng",
        image: "https://www.medigoapp.com/assets/images/pharmacy-profile.svg",
        startDate: "17/5/2022",
        endDate: "26/8/2022",
        discount: 0.5,
    },
    {
        id: 2,
        name: "Giảm 30% phí giao hàng",
        image: "https://www.medigoapp.com/assets/images/pharmacy-profile.svg",
        startDate: "17/5/2022",
        endDate: "26/8/2022",
        discount: 0.3,
    },
]